/* Generated by scripts/plates.py. One drawing per source, built from its
 * class and its fill level. A photograph in media/sources/ takes over.
 */

const PLATES = {
  "ALP": "media/plates/ALP.svg",
  "CAM": "media/plates/CAM.svg",
  "CLR": "media/plates/CLR.svg",
  "CNT": "media/plates/CNT.svg",
  "CRL": "media/plates/CRL.svg",
  "CVA": "media/plates/CVA.svg",
  "DSL": "media/plates/DSL.svg",
  "GAB": "media/plates/GAB.svg",
  "GLC": "media/plates/GLC.svg",
  "GRN": "media/plates/GRN.svg",
  "GUR": "media/plates/GUR.svg",
  "H2O": "media/plates/H2O.svg",
  "HKH": "media/plates/HKH.svg",
  "ICE": "media/plates/ICE.svg",
  "IND": "media/plates/IND.svg",
  "KRB": "media/plates/KRB.svg",
  "KRS": "media/plates/KRS.svg",
  "MEAD": "media/plates/MEAD.svg",
  "MRB": "media/plates/MRB.svg",
  "NSAS": "media/plates/NSAS.svg",
  "NSR": "media/plates/NSR.svg",
  "OGL": "media/plates/OGL.svg",
  "ORO": "media/plates/ORO.svg",
  "POW": "media/plates/POW.svg",
  "PRT": "media/plates/PRT.svg",
  "PTG": "media/plates/PTG.svg",
  "RAS": "media/plates/RAS.svg",
  "SAU": "media/plates/SAU.svg",
  "SHT": "media/plates/SHT.svg",
  "SOR": "media/plates/SOR.svg",
  "TGR": "media/plates/TGR.svg",
  "TRR": "media/plates/TRR.svg"
};
