/* Generated by scripts/photos.js. Drop a file in media/sources/ named after a
 * source's ticker and run the script again.
 */

const PHOTOS = {
  "MEAD": "media/sources/MEAD.jpg",
  "TGR": "media/sources/TGR.jpg",
  "TRR": "media/sources/TRR.jpg"
};

const PHOTO_CREDITS = {
  "MEAD": "supplied by the project, credit pending",
  "TRR": "supplied by the project, credit pending",
  "TGR": "supplied by the project, credit pending"
};
