/* Generated by scripts/plates.py. One rendered frame per source, built
 * from its class and its published fill level. A photograph in
 * media/sources/ takes its place.
 */

const PLATES = {
  "ALP": "media/plates/ALP.jpg",
  "CAM": "media/plates/CAM.jpg",
  "CLR": "media/plates/CLR.jpg",
  "CNT": "media/plates/CNT.jpg",
  "CRL": "media/plates/CRL.jpg",
  "CVA": "media/plates/CVA.jpg",
  "DSL": "media/plates/DSL.jpg",
  "GAB": "media/plates/GAB.jpg",
  "GLC": "media/plates/GLC.jpg",
  "GRN": "media/plates/GRN.jpg",
  "GUR": "media/plates/GUR.jpg",
  "H2O": "media/plates/H2O.jpg",
  "HKH": "media/plates/HKH.jpg",
  "ICE": "media/plates/ICE.jpg",
  "IND": "media/plates/IND.jpg",
  "KRB": "media/plates/KRB.jpg",
  "KRS": "media/plates/KRS.jpg",
  "MEAD": "media/plates/MEAD.jpg",
  "MRB": "media/plates/MRB.jpg",
  "NSAS": "media/plates/NSAS.jpg",
  "NSR": "media/plates/NSR.jpg",
  "OGL": "media/plates/OGL.jpg",
  "ORO": "media/plates/ORO.jpg",
  "POW": "media/plates/POW.jpg",
  "PRT": "media/plates/PRT.jpg",
  "PTG": "media/plates/PTG.jpg",
  "RAS": "media/plates/RAS.jpg",
  "SAU": "media/plates/SAU.jpg",
  "SHT": "media/plates/SHT.jpg",
  "SOR": "media/plates/SOR.jpg",
  "TGR": "media/plates/TGR.jpg",
  "TRR": "media/plates/TRR.jpg"
};
