/* Generated by scripts/extend.py. The photograph and the landscape that
 * continues from it, as one frame. Fractions are of the whole column.
 */

const WORLD = {
  src: "media/world.jpg",
  low: "media/world-half.jpg",
  blur: "media/world-blur.jpg",
  w: 1600,
  h: 6300,
  ratio: 3.9375,
  photo: 0.1429,
  stops: [{"name": "The wall", "at": 0.0}, {"name": "The river", "at": 0.22}, {"name": "The gorge", "at": 0.4}, {"name": "The confluence", "at": 0.58}, {"name": "The reserve", "at": 0.76}, {"name": "The weather", "at": 0.92}],
};
