/* Rebuilds tokens.js: every token on Robinhood Chain that has a live Uniswap v3
 * pool against WETH, with the fee tiers that actually hold liquidity.
 *
 *   node scripts/build-tokens.js
 *
 * The swap only ever routes through pools listed here, so run this again when a
 * new stock gets a pool. Needs Node 18+ (global fetch) and nothing else. */
const fs = require('fs');
const path = require('path');

const RPC = process.env.RPC_URL || 'https://rpc.mainnet.chain.robinhood.com';
const V3_FACTORY = '0x1f7d7550b1b028f7571e69a784071f0205fd2efa';
const WETH = '0x0bd7d308f8e1639fab988df18a8011f41eacad73';
const POOL_CREATED = '0x783cca1c0412dd0d695e784568c96da2e9c22ff989357a2e8b1d9b2b4e6b7118';
const FEES = [100, 500, 3000, 10000];

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
let id = 0;
async function rpc(method, params) {
  for (let attempt = 0; ; attempt++) {
    const res = await fetch(RPC, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ jsonrpc: '2.0', id: ++id, method, params })
    });
    if (res.status === 429 && attempt < 10) { await sleep(1500 * (attempt + 1)); continue; }
    const body = await res.json();
    if (body.error) throw Object.assign(new Error(body.error.message), { rpc: body.error });
    return body.result;
  }
}
const word = (a) => a.toLowerCase().replace(/^0x/, '').padStart(64, '0');
const call = (to, data) => rpc('eth_call', [{ to, data }, 'latest']);

function decodeString(hex) {
  if (!hex || hex === '0x') return '';
  const buf = Buffer.from(hex.slice(2), 'hex');
  if (buf.length >= 64) {
    const len = Number(BigInt('0x' + buf.subarray(32, 64).toString('hex')));
    if (len < 256 && 64 + len <= buf.length) return buf.subarray(64, 64 + len).toString('utf8');
  }
  return buf.toString('utf8').replace(/\0+$/, '');
}

/* PoolCreated(token0, token1, fee, tickSpacing, pool): WETH is either token0 or
   token1, so ask for each side. The node caps a query's block span, and a range
   that times out is retried in halves. */
async function wethPools(head) {
  const found = [];
  for (const side of [1, 2]) {
    const topics = [POOL_CREATED, null, null];
    topics[side] = '0x' + word(WETH);
    let from = 0, span = 10_000_000;
    while (from <= head) {
      const to = Math.min(head, from + span - 1);
      try {
        const logs = await rpc('eth_getLogs', [{ address: V3_FACTORY, fromBlock: '0x' + from.toString(16), toBlock: '0x' + to.toString(16), topics }]);
        found.push(...logs);
        from = to + 1;
      } catch (e) {
        if (span <= 50_000) throw e;
        span = Math.floor(span / 2);
      }
    }
  }
  return found.map((l) => ({
    token0: '0x' + l.topics[1].slice(26),
    token1: '0x' + l.topics[2].slice(26),
    fee: Number(BigInt(l.topics[3])),
    pool: '0x' + l.data.slice(2 + 64 + 24, 2 + 128)
  }));
}

(async () => {
  const head = Number(await rpc('eth_blockNumber', []));
  const pools = await wethPools(head);
  console.log(`${pools.length} WETH pools up to block ${head}`);

  const byToken = new Map();
  for (const p of pools) {
    const other = p.token0 === WETH ? p.token1 : p.token0;
    if (!byToken.has(other)) byToken.set(other, []);
    byToken.get(other).push(p);
  }

  const tokens = [];
  for (const [address, list] of byToken) {
    const live = [];
    for (const p of list) {
      const liq = BigInt(await call(p.pool, '0x1a686502'));
      if (liq > 0n) live.push({ fee: p.fee, pool: p.pool, liquidity: liq.toString() });
    }
    if (!live.length) continue;
    let symbol, name, decimals;
    try {
      symbol = decodeString(await call(address, '0x95d89b41'));
      name = decodeString(await call(address, '0x06fdde03'));
      decimals = Number(BigInt(await call(address, '0x313ce567')));
    } catch { continue; }
    live.sort((a, b) => FEES.indexOf(a.fee) - FEES.indexOf(b.fee));
    tokens.push({ symbol, name, address, decimals, pools: live });
    console.log(symbol.padEnd(8), name, live.map((p) => p.fee).join(','));
  }
  tokens.sort((a, b) => a.symbol.localeCompare(b.symbol));

  const out = `/* Generated by scripts/build-tokens.js at block ${head}. Do not edit by hand. */\n` +
    `window.CHAIN_TOKENS = ${JSON.stringify(tokens, null, 1)};\n`;
  fs.writeFileSync(path.join(__dirname, '..', 'tokens.js'), out);
  console.log(`wrote ${tokens.length} tokens`);
})().catch((e) => { console.error(e); process.exit(1); });
