#!/usr/bin/env node
/* ===========================================================================
   facades.js — one small SVG elevation per building, from the facts in
   data/buildings.json: floors, apartments per floor, an era-appropriate roof.
   Deterministic: the same building draws the same façade every time.
   Writes data/facades.js (window.RENTA_FACADES) for the pages to inline.
   =========================================================================== */
'use strict';
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const B = JSON.parse(fs.readFileSync(path.join(root, 'data', 'buildings.json'), 'utf8'));

function facade(b, W = 120, H = 96) {
  const floors = b.floors, perFloor = Math.max(2, Math.round(b.units / floors));
  const era = b.built < 1915 ? 'old' : b.built < 1945 ? 'inter' : 'post';
  const bw = 88, bx = (W - bw) / 2;
  const roofH = era === 'old' ? 14 : era === 'inter' ? 8 : 4;
  const floorH = (H - roofH - 10) / floors;
  const p = [];
  p.push(`<svg viewBox="0 0 ${W} ${H}" class="rt-facade" aria-hidden="true">`);
  /* ground */
  p.push(`<rect x="0" y="${H - 8}" width="${W}" height="8" fill="#0B1F38"/>`);
  /* body */
  const bodyTop = roofH + 2;
  p.push(`<rect x="${bx}" y="${bodyTop}" width="${bw}" height="${H - 8 - bodyTop}" fill="#7E6A55"/>`);
  /* roof */
  if (era === 'old') p.push(`<path d="M${bx - 4},${bodyTop} L${W / 2},1 L${bx + bw + 4},${bodyTop}Z" fill="#5C4B3B"/>`);
  else if (era === 'inter') p.push(`<rect x="${bx - 3}" y="${bodyTop - roofH}" width="${bw + 6}" height="${roofH}" rx="2" fill="#5C4B3B"/>`);
  else p.push(`<rect x="${bx - 2}" y="${bodyTop - roofH}" width="${bw + 4}" height="${roofH}" fill="#5C4B3B"/>`);
  /* string courses on the old ones */
  if (era === 'old') for (let f = 1; f < floors; f++) p.push(`<rect x="${bx}" y="${(bodyTop + f * floorH).toFixed(1)}" width="${bw}" height="1.2" fill="#6B5947"/>`);
  /* windows: a lit one per floor picked by the building's own seed */
  let seed = b.built * 7 + b.units * 13;
  const rnd = () => { seed = (seed * 1103515245 + 12345) & 0x7fffffff; return seed / 0x7fffffff; };
  const ww = era === 'post' ? 14 : 9, wh = era === 'post' ? 9 : 13;
  const gap = (bw - perFloor * ww) / (perFloor + 1);
  for (let f = 0; f < floors; f++) {
    const y = bodyTop + f * floorH + (floorH - wh) / 2;
    const lit = Math.floor(rnd() * perFloor);
    for (let i = 0; i < perFloor; i++) {
      const x = bx + gap + i * (ww + gap);
      const ground = f === floors - 1 && i === Math.floor(perFloor / 2);
      if (ground) { p.push(`<rect x="${(x + ww / 2 - 5).toFixed(1)}" y="${(H - 8 - 16).toFixed(1)}" width="10" height="16" rx="1" fill="#0F2A45"/>`); continue; }
      p.push(`<rect x="${x.toFixed(1)}" y="${y.toFixed(1)}" width="${ww}" height="${wh}" rx="${era === 'old' ? 3 : 1}" fill="${i === lit && rnd() < .8 ? '#BEE9F8' : '#0F2A45'}"/>`);
    }
  }
  p.push('</svg>');
  return p.join('');
}

const out = {};
for (const b of B) out[b.id] = facade(b);
fs.writeFileSync(path.join(root, 'data', 'facades.js'), '/* generated by scripts/facades.js — do not edit */\nwindow.RENTA_FACADES = ' + JSON.stringify(out) + ';\n');
fs.writeFileSync(path.join(root, 'data', 'facades.json'), JSON.stringify(out, null, 1) + '\n');
console.error('drew', Object.keys(out).length, 'façades');
