import "@fontsource-variable/inter";
import "@fontsource-variable/space-grotesk";
import "@fontsource/jetbrains-mono/400.css";
import "@fontsource/jetbrains-mono/500.css";
import "./globals.css";
import type { Metadata, Viewport } from "next";
import { Providers } from "@/components/providers/Providers";

// Render every page per request so a new deploy shows up on the next reload, instead of
// prerendered HTML that browsers and proxies keep for a year. Hashed JS/CSS stay cached.
export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000"),
  // Browser tabs only ever show the site name; link previews keep their own titles below.
  title: { default: "Stepit", template: "Stepit" },
  description:
    "Stepit turns your daily steps into crypto rewards. Explore the outdoors, stay active and earn a share of platform fees.",
  openGraph: {
    // The preview image is generated by app/opengraph-image.tsx.
    title: "Stepit · Walk. Upload. Earn USDG.",
    description: "Upload your daily steps with a screenshot and get paid in USDG on Robinhood Chain.",
    type: "website",
  },
  twitter: { card: "summary_large_image" },
  icons: { icon: "/icon.svg" },
};

export const viewport: Viewport = {
  themeColor: "#060807",
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
