const fs = require('fs'), path = require('path');
const solc = require('solc');
const src = fs.readFileSync(path.join(__dirname, 'Hydropad.sol'), 'utf8');
const input = {
  language: 'Solidity',
  sources: { 'Hydropad.sol': { content: src } },
  settings: {
    optimizer: { enabled: true, runs: 200 },
    evmVersion: 'paris',
    outputSelection: { '*': { '*': ['abi', 'evm.bytecode.object'] } },
  },
};
const out = JSON.parse(solc.compile(JSON.stringify(input)));
for (const e of out.errors || []) console.log(e.severity.toUpperCase() + ':', e.formattedMessage.trim().split('\n')[0]);
if ((out.errors || []).some(e => e.severity === 'error')) process.exit(1);
const c = out.contracts['Hydropad.sol'];
const artifact = {
  compiler: 'solc ' + solc.version(),
  Hydropad: { abi: c.Hydropad.abi, bytecode: '0x' + c.Hydropad.evm.bytecode.object },
  HydropadToken: { abi: c.HydropadToken.abi },
};
fs.writeFileSync(path.join(__dirname, '..', 'contract.js'),
  '/* Generated by contracts/compile.js. Do not edit by hand.\n * Solidity ' + solc.version() + ', optimizer on (200 runs), evmVersion paris.\n */\n\nconst HYDROPAD = ' + JSON.stringify(artifact, null, 2) + ';\n');
console.log('bytecode bytes:', c.Hydropad.evm.bytecode.object.length / 2);
