/* Generated by scripts/build-register.py. Do not edit by hand.
 *
 * Source: Global Power Plant Database v1.3.0, World Resources Institute, CC BY 4.0 — https://datasets.wri.org/dataset/globalpowerplantdatabase
 */

const ATTRIBUTION = "Global Power Plant Database v1.3.0, World Resources Institute, CC BY 4.0 \u2014 https://datasets.wri.org/dataset/globalpowerplantdatabase";

const PLANTS = [
 {
  "t": "GEYS",
  "n": "Geysers",
  "c": "Geothermal",
  "l": "United States of America",
  "mw": 1163.0,
  "g": [
   38.777,
   -122.745
  ],
  "y": 1979,
  "o": "Geysers Power Co LLC",
  "src": "U.S. Energy Information Administration",
  "url": "http://www.eia.gov/electricity/data/browser/",
  "gen": {
   "year": 2019,
   "gwh": 4351.4
  },
  "id": "USA0000286"
 },
 {
  "t": "UL",
  "n": "Unified Leyte",
  "c": "Geothermal",
  "l": "Philippines",
  "mw": 610.2,
  "g": [
   11.1308,
   124.6553
  ],
  "y": null,
  "o": null,
  "src": "Philippines Department of Energy",
  "url": "https://www.doe.gov.ph/list-existing-power-plants",
  "gen": null,
  "id": "WRI1001943"
 },
 {
  "t": "MAKB",
  "n": "Makban",
  "c": "Geothermal",
  "l": "Philippines",
  "mw": 442.8,
  "g": [
   14.0881,
   121.2264
  ],
  "y": null,
  "o": null,
  "src": "Philippines Department of Energy",
  "url": "https://www.doe.gov.ph/list-existing-power-plants",
  "gen": null,
  "id": "WRI1001888"
 },
 {
  "t": "TIWI",
  "n": "TIWI",
  "c": "Geothermal",
  "l": "Philippines",
  "mw": 234.0,
  "g": [
   13.4655,
   123.6486
  ],
  "y": null,
  "o": null,
  "src": "Philippines Department of Energy",
  "url": "https://www.doe.gov.ph/list-existing-power-plants",
  "gen": null,
  "id": "WRI1001890"
 },
 {
  "t": "HELL",
  "n": "Hellisheiði",
  "c": "Geothermal",
  "l": "Iceland",
  "mw": 213.0,
  "g": [
   64.0373,
   -21.4007
  ],
  "y": 2006,
  "o": "Orkuveita Reykjavíkur",
  "src": "Iceland Energy Portal",
  "url": "http://gilslaug.orkugardur.is/vefsja/orkuvefsja_en.html",
  "gen": null,
  "id": "WRI1002796"
 },
 {
  "t": "PG",
  "n": "Palinpinon GPP",
  "c": "Geothermal",
  "l": "Philippines",
  "mw": 192.5,
  "g": [
   9.3031,
   123.2141
  ],
  "y": null,
  "o": null,
  "src": "Philippines Department of Energy",
  "url": "https://www.doe.gov.ph/list-existing-power-plants",
  "gen": null,
  "id": "WRI1001941"
 },
 {
  "t": "OI",
  "n": "Olkaria I",
  "c": "Geothermal",
  "l": "Kenya",
  "mw": 185.0,
  "g": [
   -0.8933,
   36.3086
  ],
  "y": 1981,
  "o": "Kenya Electric Generating Company",
  "src": "Kenya Electricity Generating Company",
  "url": "http://www.kengen.co.ke/?q=kengen-download",
  "gen": null,
  "id": "WRI1061218"
 },
 {
  "t": "OIU",
  "n": "Olkaria I units 4 & 5",
  "c": "Geothermal",
  "l": "Kenya",
  "mw": 140.0,
  "g": [
   -0.891,
   36.2961
  ],
  "y": 2015,
  "o": "Kenya Electric Generating Company",
  "src": "Kenya Electricity Generating Company",
  "url": "http://www.kengen.co.ke/?q=content/geothermal-plants",
  "gen": null,
  "id": "WRI1061219"
 },
 {
  "t": "OLKA",
  "n": "Olkaria IV",
  "c": "Geothermal",
  "l": "Kenya",
  "mw": 140.0,
  "g": [
   -0.9186,
   36.3338
  ],
  "y": 2014,
  "o": "Kenya Electric Generating Company",
  "src": "Kenya Electricity Generating Company",
  "url": "http://www.kengen.co.ke/?q=content/geothermal-plants",
  "gen": null,
  "id": "WRI1061217"
 },
 {
  "t": "OO",
  "n": "Olkaria III (Orpower 4)",
  "c": "Geothermal",
  "l": "Kenya",
  "mw": 139.0,
  "g": [
   -0.8905,
   36.2892
  ],
  "y": 2015,
  "o": "Ormat Technologies Inc",
  "src": "Ormat ; Kenya Power",
  "url": "http://www.ormat.com/en/projects/all/main/ ; http://www.kplc.co.ke/AR2016/KPLC%202016%20Annual%20Report%20Upload.pdf",
  "gen": null,
  "id": "WRI1061220"
 },
 {
  "t": "NAP",
  "n": "Nga Awa Purua",
  "c": "Geothermal",
  "l": "New Zealand",
  "mw": 138.0,
  "g": [
   -38.6143,
   176.1825
  ],
  "y": 2010,
  "o": "Mercury Energy",
  "src": "Mercury Energy",
  "url": "https://www.mercury.co.nz/About/Renewable-Energy/Geothermal-Generation.aspx",
  "gen": null,
  "id": "WRI1000326"
 },
 {
  "t": "OHAA",
  "n": "Ohaaki",
  "c": "Geothermal",
  "l": "New Zealand",
  "mw": 122.0,
  "g": [
   -38.5279,
   176.2937
  ],
  "y": 1984,
  "o": "Contact Energy",
  "src": "Contact Energy",
  "url": "https://contact.co.nz/corporate/about/our-company/powerstations",
  "gen": null,
  "id": "WRI1000332"
 },
 {
  "t": "NESJ",
  "n": "Nesjavellir",
  "c": "Geothermal",
  "l": "Iceland",
  "mw": 120.0,
  "g": [
   64.1081,
   -21.2567
  ],
  "y": 1998,
  "o": "Orkuveita Reykjavíkur",
  "src": "Iceland Energy Portal",
  "url": "http://gilslaug.orkugardur.is/vefsja/orkuvefsja_en.html",
  "gen": null,
  "id": "WRI1002805"
 },
 {
  "t": "MOKA",
  "n": "mokai",
  "c": "Geothermal",
  "l": "New Zealand",
  "mw": 112.0,
  "g": [
   -38.5312,
   175.9268
  ],
  "y": 2000,
  "o": "Mercury Energy",
  "src": "Mercury Energy",
  "url": "https://www.mercury.co.nz/About/Renewable-Energy/Geothermal-Generation.aspx",
  "gen": null,
  "id": "WRI1000320"
 },
 {
  "t": "REYK",
  "n": "Reykjanes",
  "c": "Geothermal",
  "l": "Iceland",
  "mw": 100.0,
  "g": [
   63.8251,
   -22.6848
  ],
  "y": 1977,
  "o": "HS Orka",
  "src": "Iceland Energy Portal",
  "url": "http://gilslaug.orkugardur.is/vefsja/orkuvefsja_en.html",
  "gen": null,
  "id": "WRI1002806"
 },
 {
  "t": "KAWE",
  "n": "Kawerau",
  "c": "Geothermal",
  "l": "New Zealand",
  "mw": 100.0,
  "g": [
   -38.0631,
   176.7272
  ],
  "y": 2008,
  "o": "Mercury Energy",
  "src": "Mercury Energy",
  "url": "https://www.mercury.co.nz/About/Renewable-Energy/Geothermal-Generation.aspx",
  "gen": null,
  "id": "WRI1000327"
 },
 {
  "t": "KIZI",
  "n": "Kizildere 2",
  "c": "Geothermal",
  "l": "Turkey",
  "mw": 80.0,
  "g": [
   37.9499,
   28.8354
  ],
  "y": 2013,
  "o": "Zorlu Enerji",
  "src": "Enerji Atlasi",
  "url": "http://www.enerjiatlasi.com/jeotermal/zorlu-enerji-kizildere-2-jeotermal-enerji-santrali.html",
  "gen": null,
  "id": "WRI1018955"
 },
 {
  "t": "SVAR",
  "n": "Svartsengi",
  "c": "Geothermal",
  "l": "Iceland",
  "mw": 76.0,
  "g": [
   63.8788,
   -22.4332
  ],
  "y": 1977,
  "o": "HS Orka",
  "src": "Iceland Energy Portal",
  "url": "http://gilslaug.orkugardur.is/vefsja/orkuvefsja_en.html",
  "gen": null,
  "id": "WRI1002810"
 },
 {
  "t": "PAMU",
  "n": "Pamukören",
  "c": "Geothermal",
  "l": "Turkey",
  "mw": 68.0,
  "g": [
   37.9171,
   28.5297
  ],
  "y": 2014,
  "o": "Çelikler Enerji",
  "src": "Enerji Atlasi",
  "url": "http://www.enerjiatlasi.com/jeotermal/pamukoren-jeotermal-enerji-santrali.html",
  "gen": null,
  "id": "WRI1018956"
 },
 {
  "t": "YN",
  "n": "Yanaizu-Nishiyama",
  "c": "Geothermal",
  "l": "Japan",
  "mw": 65.0,
  "g": [
   37.44,
   139.694
  ],
  "y": 1995,
  "o": "KYUSHU ELECTRIC POWER CO",
  "src": "Japanese Electric Power Information Center",
  "url": "https://www.jepic.or.jp/en/",
  "gen": null,
  "id": "WRI1020129"
 },
 {
  "t": "NR",
  "n": "Nuova Radicondoli",
  "c": "Geothermal",
  "l": "Italy",
  "mw": 59.0,
  "g": [
   43.1935,
   11.0446
  ],
  "y": 2002,
  "o": null,
  "src": "ENTSOE",
  "url": "https://transparency.entsoe.eu/generation/r2/installedCapacityPerProductionUnit/show",
  "gen": null,
  "id": "WRI1021348"
 },
 {
  "t": "FARI",
  "n": "Farinello",
  "c": "Geothermal",
  "l": "Italy",
  "mw": 54.0,
  "g": [
   43.2388,
   10.9047
  ],
  "y": 1995,
  "o": null,
  "src": "ENTSOE",
  "url": "https://transparency.entsoe.eu/generation/r2/installedCapacityPerProductionUnit/show",
  "gen": null,
  "id": "WRI1021364"
 },
 {
  "t": "MORI",
  "n": "Mori",
  "c": "Geothermal",
  "l": "Japan",
  "mw": 50.0,
  "g": [
   42.1331,
   140.4553
  ],
  "y": 1982,
  "o": "TOHOKU ELECTRIC POWER CO",
  "src": "Japanese Electric Power Information Center",
  "url": "https://www.jepic.or.jp/en/",
  "gen": null,
  "id": "WRI1020120"
 },
 {
  "t": "NS",
  "n": "Nuova Serrazzano",
  "c": "Geothermal",
  "l": "Italy",
  "mw": 49.0,
  "g": [
   43.204,
   10.8003
  ],
  "y": 2002,
  "o": null,
  "src": "ENTSOE",
  "url": "https://transparency.entsoe.eu/generation/r2/installedCapacityPerProductionUnit/show",
  "gen": null,
  "id": "WRI1021382"
 },
 {
  "t": "BAGN",
  "n": "Bagnore 4",
  "c": "Geothermal",
  "l": "Italy",
  "mw": 39.0,
  "g": [
   42.8416,
   11.5588
  ],
  "y": 1998,
  "o": null,
  "src": "ENTSOE",
  "url": "https://transparency.entsoe.eu/generation/r2/installedCapacityPerProductionUnit/show",
  "gen": null,
  "id": "WRI1021456"
 },
 {
  "t": "TG",
  "n": "Three Gorges Dam",
  "c": "Hydro",
  "l": "China",
  "mw": 22500.0,
  "g": [
   30.8235,
   111.0032
  ],
  "y": 2003,
  "o": null,
  "src": "China Three Gorges Corporation",
  "url": "http://www.ctgpc.com.cn/sx/sxgczds.php?mClassId=015004",
  "gen": null,
  "id": "WRI1000452"
 },
 {
  "t": "TUCU",
  "n": "Tucuruí",
  "c": "Hydro",
  "l": "Brazil",
  "mw": 8535.0,
  "g": [
   -3.8322,
   -49.6522
  ],
  "y": 1984,
  "o": null,
  "src": "Agência Nacional de Energia Elétrica (Brazil)",
  "url": "http://www2.aneel.gov.br/aplicacoes/capacidadebrasil/capacidadebrasil.cfm",
  "gen": null,
  "id": "BRA0002889"
 },
 {
  "t": "IPB",
  "n": "Itaipu (Parte Brasileira)",
  "c": "Hydro",
  "l": "Brazil",
  "mw": 7000.0,
  "g": [
   -25.4269,
   -54.5931
  ],
  "y": 1989,
  "o": null,
  "src": "Agência Nacional de Energia Elétrica (Brazil)",
  "url": "http://www2.aneel.gov.br/aplicacoes/capacidadebrasil/capacidadebrasil.cfm",
  "gen": null,
  "id": "BRA0001161"
 },
 {
  "t": "GC",
  "n": "Grand Coulee",
  "c": "Hydro",
  "l": "United States of America",
  "mw": 6809.0,
  "g": [
   47.9575,
   -118.9773
  ],
  "y": 1967,
  "o": "U S Bureau of Reclamation",
  "src": "U.S. Energy Information Administration",
  "url": "http://www.eia.gov/electricity/data/browser/",
  "gen": {
   "year": 2019,
   "gwh": 16639.4
  },
  "id": "USA0006163"
 },
 {
  "t": "RB",
  "n": "Robert-Bourassa",
  "c": "Hydro",
  "l": "Canada",
  "mw": 5616.0,
  "g": [
   53.7818,
   -77.5305
  ],
  "y": null,
  "o": "Hydro-Québec",
  "src": "Natural Resources Canada",
  "url": "http://ftp.maps.canada.ca/pub/nacei_cnaie/energy_infrastructure/PowerPlantsAllGE100MW_NorthAmerica_201708.xlsx",
  "gen": null,
  "id": "CAN0002223"
 },
 {
  "t": "JIRA",
  "n": "Jirau",
  "c": "Hydro",
  "l": "Brazil",
  "mw": 3750.0,
  "g": [
   -9.2664,
   -64.6478
  ],
  "y": 2013,
  "o": null,
  "src": "Agência Nacional de Energia Elétrica (Brazil)",
  "url": "http://www2.aneel.gov.br/aplicacoes/capacidadebrasil/capacidadebrasil.cfm",
  "gen": null,
  "id": "BRA0029736"
 },
 {
  "t": "SA",
  "n": "Santo Antônio",
  "c": "Hydro",
  "l": "Brazil",
  "mw": 3568.0,
  "g": [
   -8.8011,
   -63.9497
  ],
  "y": 2012,
  "o": null,
  "src": "Agência Nacional de Energia Elétrica (Brazil)",
  "url": "http://www2.aneel.gov.br/aplicacoes/capacidadebrasil/capacidadebrasil.cfm",
  "gen": null,
  "id": "BRA0029707"
 },
 {
  "t": "NURE",
  "n": "Nurek",
  "c": "Hydro",
  "l": "Tajikistan",
  "mw": 3015.0,
  "g": [
   38.3717,
   69.3481
  ],
  "y": 1972,
  "o": "Barki Tojik",
  "src": "Energy Charter Secretariat",
  "url": "http://www.energycharter.org/fileadmin/DocumentsMedia/IDEER/IDEER-Tajikistan_2013_en.pdf",
  "gen": null,
  "id": "WRI1000349"
 },
 {
  "t": "BC",
  "n": "Bath County",
  "c": "Hydro",
  "l": "United States of America",
  "mw": 2862.0,
  "g": [
   38.2089,
   -79.8
  ],
  "y": 1986,
  "o": "Virginia Electric & Power Co",
  "src": "U.S. Energy Information Administration",
  "url": "http://www.eia.gov/electricity/data/browser/",
  "gen": {
   "year": 2019,
   "gwh": -780.3
  },
  "id": "USA0006167"
 },
 {
  "t": "GRAN",
  "n": "La Grande-4",
  "c": "Hydro",
  "l": "Canada",
  "mw": 2779.0,
  "g": [
   53.8864,
   -73.466
  ],
  "y": null,
  "o": "Hydro-Québec",
  "src": "Natural Resources Canada",
  "url": "http://ftp.maps.canada.ca/pub/nacei_cnaie/energy_infrastructure/PowerPlantsAllGE100MW_NorthAmerica_201708.xlsx",
  "gen": null,
  "id": "CAN0002176"
 },
 {
  "t": "CJ",
  "n": "Chief Joseph",
  "c": "Hydro",
  "l": "United States of America",
  "mw": 2456.2,
  "g": [
   47.9951,
   -119.6404
  ],
  "y": 1965,
  "o": "USACE Northwestern Division",
  "src": "U.S. Energy Information Administration",
  "url": "http://www.eia.gov/electricity/data/browser/",
  "gen": {
   "year": 2019,
   "gwh": 9854.0
  },
  "id": "USA0003921"
 },
 {
  "t": "RMN",
  "n": "Robert Moses Niagara",
  "c": "Hydro",
  "l": "United States of America",
  "mw": 2429.1,
  "g": [
   43.1427,
   -79.0394
  ],
  "y": 1961,
  "o": "New York Power Authority",
  "src": "U.S. Energy Information Administration",
  "url": "http://www.eia.gov/electricity/data/browser/",
  "gen": {
   "year": 2019,
   "gwh": 16909.3
  },
  "id": "USA0002693"
 },
 {
  "t": "KC",
  "n": "Koyna Complex",
  "c": "Hydro",
  "l": "India",
  "mw": 1956.0,
  "g": [
   17.4599,
   73.684
  ],
  "y": 1984,
  "o": null,
  "src": "Central Electricity Authority",
  "url": "http://www.cea.nic.in/",
  "gen": {
   "year": 2018,
   "gwh": 2754.1
  },
  "id": "IND0000217"
 },
 {
  "t": "NJ",
  "n": "Nathpa Jhakri",
  "c": "Hydro",
  "l": "India",
  "mw": 1500.0,
  "g": [
   31.564,
   77.98
  ],
  "y": 2003,
  "o": null,
  "src": "Central Electricity Authority",
  "url": "http://www.cea.nic.in/",
  "gen": {
   "year": 2018,
   "gwh": 6474.6
  },
  "id": "IND0000294"
 },
 {
  "t": "BHAK",
  "n": "Bhakra",
  "c": "Hydro",
  "l": "India",
  "mw": 1379.0,
  "g": [
   31.4107,
   76.4328
  ],
  "y": 1964,
  "o": null,
  "src": "Central Electricity Authority",
  "url": "http://www.cea.nic.in/",
  "gen": {
   "year": 2018,
   "gwh": 4217.0
  },
  "id": "IND0000047"
 },
 {
  "t": "ALDE",
  "n": "Aldeadavila II 2",
  "c": "Hydro",
  "l": "Spain",
  "mw": 1226.4,
  "g": [
   41.2117,
   -6.6856
  ],
  "y": 1986,
  "o": "IBERDROLA GENERACION  S.A.",
  "src": "Red Eléctrica de España",
  "url": "http://www.ree.es/en/statistical-data-of-spanish-electrical-system/annual-report/preliminary-report-spanish-electricity-system-2015",
  "gen": {
   "year": 2017,
   "gwh": 1196.2
  },
  "id": "WRI1006178"
 },
 {
  "t": "SSR",
  "n": "S.sarovar Rbph",
  "c": "Hydro",
  "l": "India",
  "mw": 1200.0,
  "g": [
   21.8301,
   73.7501
  ],
  "y": 2005,
  "o": null,
  "src": "Central Electricity Authority",
  "url": "http://www.cea.nic.in/",
  "gen": {
   "year": 2017,
   "gwh": 374.7
  },
  "id": "IND0000383"
 },
 {
  "t": "BAOQ",
  "n": "Baoquan",
  "c": "Hydro",
  "l": "China",
  "mw": 1200.0,
  "g": [
   35.48,
   113.48
  ],
  "y": 2011,
  "o": null,
  "src": "HydroChina Corporation",
  "url": "https://web.archive.org/web/20140407100033/http://www.hydrochina.com.cn/gcjs/dbx/zj/2.jsp",
  "gen": null,
  "id": "WRI1000559"
 },
 {
  "t": "HPFI",
  "n": "HPP Portile de Fier I",
  "c": "Hydro",
  "l": "Romania",
  "mw": 1161.0,
  "g": [
   44.6733,
   22.532
  ],
  "y": 1972,
  "o": null,
  "src": "ENTSOE",
  "url": "https://transparency.entsoe.eu/generation/r2/installedCapacityPerProductionUnit/show",
  "gen": {
   "year": 2017,
   "gwh": 4707.1
  },
  "id": "WRI1019095"
 },
 {
  "t": "PV",
  "n": "PSW Vianden",
  "c": "Hydro",
  "l": "Germany",
  "mw": 1096.0,
  "g": [
   49.9523,
   6.1783
  ],
  "y": null,
  "o": "SociÃ©tÃ© Electrique de l'Our S.A.",
  "src": "Open Power System Data",
  "url": "http://data.open-power-system-data.org/",
  "gen": {
   "year": 2016,
   "gwh": 1416.5
  },
  "id": "WRI1006007"
 },
 {
  "t": "HDI",
  "n": "HE Djerdap I",
  "c": "Hydro",
  "l": "Serbia",
  "mw": 1086.0,
  "g": [
   44.6684,
   22.5268
  ],
  "y": null,
  "o": null,
  "src": "ENTSOE",
  "url": "https://transparency.entsoe.eu/generation/r2/installedCapacityPerProductionUnit/show",
  "gen": {
   "year": 2015,
   "gwh": 12.7
  },
  "id": "WRI1020277"
 },
 {
  "t": "NT",
  "n": "Nam Theun 2",
  "c": "Hydro",
  "l": "Laos",
  "mw": 1070.0,
  "g": [
   18.4375,
   102.947
  ],
  "y": 2010,
  "o": "EDF",
  "src": "Department of Energy Business",
  "url": "http://www.poweringprogress.org/index.php?option=com_content&view=article&id=104:nam-theun-2-1070mw&catid=128:operational-projects&Itemid=73",
  "gen": null,
  "id": "WRI1001053"
 },
 {
  "t": "GOLD",
  "n": "Goldisthal",
  "c": "Hydro",
  "l": "Germany",
  "mw": 1052.0,
  "g": [
   50.5098,
   11.0209
  ],
  "y": null,
  "o": "Vattenfall Europe Generation AG",
  "src": "Open Power System Data",
  "url": "http://data.open-power-system-data.org/",
  "gen": {
   "year": 2017,
   "gwh": 1783.9
  },
  "id": "WRI1005702"
 },
 {
  "t": "MARK",
  "n": "Markersbach",
  "c": "Hydro",
  "l": "Germany",
  "mw": 1045.2,
  "g": [
   50.5194,
   12.8798
  ],
  "y": 1980,
  "o": "Vattenfall Europe Generation AG",
  "src": "Open Power System Data",
  "url": "http://data.open-power-system-data.org/",
  "gen": {
   "year": 2017,
   "gwh": 613.0
  },
  "id": "WRI1005937"
 },
 {
  "t": "AKSO",
  "n": "Aksombo",
  "c": "Hydro",
  "l": "Ghana",
  "mw": 1038.0,
  "g": [
   6.2998,
   0.0594
  ],
  "y": 1961,
  "o": null,
  "src": "Volta River Authority",
  "url": "http://www.vra.com/resources/annual_reports/2014%20Annual%20Report.pdf",
  "gen": {
   "year": 2014,
   "gwh": 6508.0
  },
  "id": "WRI1000011"
 },
 {
  "t": "TI",
  "n": "Tai'in",
  "c": "Hydro",
  "l": "China",
  "mw": 1000.0,
  "g": [
   36.23,
   117.05
  ],
  "y": 2007,
  "o": null,
  "src": "HydroChina Corporation",
  "url": "http://jyll.ifund.jrj.com.cn/forumjyll/topic43765.html",
  "gen": null,
  "id": "WRI1000555"
 },
 {
  "t": "DE",
  "n": "Daguan Erchang",
  "c": "Hydro",
  "l": "Taiwan",
  "mw": 1000.0,
  "g": [
   23.8542,
   120.8701
  ],
  "y": 1985,
  "o": null,
  "src": "Bureau of Ministry  Energy  and Economic Affairs",
  "url": "http://web3.moeaboe.gov.tw/ECW/english/content/ContentLink.aspx?menu_id=1577",
  "gen": null,
  "id": "WRI1000441"
 },
 {
  "t": "KG",
  "n": "Kafue Gorge",
  "c": "Hydro",
  "l": "Zambia",
  "mw": 990.0,
  "g": [
   -15.8089,
   28.4199
  ],
  "y": 1971,
  "o": "ZESCO",
  "src": "Energy Regulation Board of Zambia",
  "url": "http://www.erb.org.zm/reports/EnergySectorReport2014.pdf",
  "gen": null,
  "id": "WRI1000022"
 },
 {
  "t": "WEHR",
  "n": "Wehr",
  "c": "Hydro",
  "l": "Germany",
  "mw": 910.0,
  "g": [
   47.6453,
   7.9182
  ],
  "y": 1975,
  "o": "Schluchseewerk Aktiengesellschaft",
  "src": "Open Power System Data",
  "url": "http://data.open-power-system-data.org/",
  "gen": {
   "year": 2017,
   "gwh": 1193.9
  },
  "id": "WRI1006132"
 },
 {
  "t": "PH",
  "n": "Plavinas HPP",
  "c": "Hydro",
  "l": "Latvia",
  "mw": 894.0,
  "g": [
   56.583,
   25.2394
  ],
  "y": null,
  "o": null,
  "src": "ENTSOE",
  "url": "https://transparency.entsoe.eu/generation/r2/installedCapacityPerProductionUnit/show",
  "gen": {
   "year": 2017,
   "gwh": 396.0
  },
  "id": "WRI1022436"
 },
 {
  "t": "VILL",
  "n": "Villarino 4",
  "c": "Hydro",
  "l": "Spain",
  "mw": 850.9,
  "g": [
   41.2669,
   -6.3078
  ],
  "y": 1970,
  "o": "IBERDROLA GENERACION  S.A.",
  "src": "Red Eléctrica de España",
  "url": "http://www.ree.es/en/statistical-data-of-spanish-electrical-system/annual-report/preliminary-report-spanish-electricity-system-2015",
  "gen": {
   "year": 2017,
   "gwh": 1160.0
  },
  "id": "WRI1008033"
 },
 {
  "t": "AMM",
  "n": "Antunez de Mayolo (Mantaro)",
  "c": "Hydro",
  "l": "Peru",
  "mw": 798.0,
  "g": [
   -12.4644,
   -74.7865
  ],
  "y": 1978,
  "o": "Electroperú S. A.",
  "src": "Peru Ministry of Energy and Mines",
  "url": "http://www.minem.gob.pe/minem/archivos/Capitulo%203%20Generacion%20electrica%202015%20FINAL.pdf",
  "gen": {
   "year": 2015,
   "gwh": 5441.0
  },
  "id": "WRI1022054"
 },
 {
  "t": "FRAD",
  "n": "Frades II",
  "c": "Hydro",
  "l": "Portugal",
  "mw": 780.0,
  "g": [
   41.6934,
   -8.0279
  ],
  "y": null,
  "o": null,
  "src": "ENTSOE",
  "url": "https://transparency.entsoe.eu/generation/r2/installedCapacityPerProductionUnit/show?name=&defaultValue=true&viewType=TABLE&areaType=BZN&atch=false&dateTime.dateTime=01.01.2016+00:00|UTC|YEAR&area.values=CTY|10YPT-REN------W!BZN|10YPT-REN------W&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19&DataTables_Table_0_length=50#",
  "gen": {
   "year": 2017,
   "gwh": 207.5
  },
  "id": "WRI1023232"
 },
 {
  "t": "NN",
  "n": "Nam Ngum 2",
  "c": "Hydro",
  "l": "Laos",
  "mw": 735.0,
  "g": [
   19.3394,
   102.6107
  ],
  "y": 2011,
  "o": null,
  "src": "Department of Energy Business",
  "url": "http://www.poweringprogress.org/index.php?view=article&catid=129%3Aproject-under-construction&id=271%3Anam-ngum-2-615mw&option=com_content&Itemid=74",
  "gen": null,
  "id": "WRI1001059"
 },
 {
  "t": "ARNO",
  "n": "Żarnowiec",
  "c": "Hydro",
  "l": "Poland",
  "mw": 716.0,
  "g": [
   54.7224,
   18.0825
  ],
  "y": 1983,
  "o": "PGE",
  "src": "ENTSOE",
  "url": "https://transparency.entsoe.eu/generation/r2/installedCapacityPerProductionUnit/show",
  "gen": {
   "year": 2017,
   "gwh": 256.0
  },
  "id": "WRI1019043"
 },
 {
  "t": "SANG",
  "n": "Sangtuda 1",
  "c": "Hydro",
  "l": "Tajikistan",
  "mw": 700.0,
  "g": [
   38.0435,
   69.0583
  ],
  "y": 2009,
  "o": "IPP",
  "src": "Energy Charter Secretariat",
  "url": "http://www.energycharter.org/fileadmin/DocumentsMedia/IDEER/IDEER-Tajikistan_2013_en.pdf",
  "gen": null,
  "id": "WRI1000350"
 },
 {
  "t": "MC",
  "n": "LA Muela Cortes 1",
  "c": "Hydro",
  "l": "Spain",
  "mw": 634.0,
  "g": [
   39.2628,
   -0.9192
  ],
  "y": 1989,
  "o": "IBERDROLA GENERACION  S.A.",
  "src": "Red Eléctrica de España",
  "url": "http://www.ree.es/en/statistical-data-of-spanish-electrical-system/annual-report/preliminary-report-spanish-electricity-system-2015",
  "gen": {
   "year": 2017,
   "gwh": 1774.5
  },
  "id": "WRI1006586"
 },
 {
  "t": "AL",
  "n": "Alto Lindoso",
  "c": "Hydro",
  "l": "Portugal",
  "mw": 630.0,
  "g": [
   41.8693,
   -8.2029
  ],
  "y": null,
  "o": null,
  "src": "ENTSOE",
  "url": "https://transparency.entsoe.eu/generation/r2/installedCapacityPerProductionUnit/show?name=&defaultValue=true&viewType=TABLE&areaType=BZN&atch=false&dateTime.dateTime=01.01.2016+00:00|UTC|YEAR&area.values=CTY|10YPT-REN------W!BZN|10YPT-REN------W&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19&DataTables_Table_0_length=50#",
  "gen": {
   "year": 2017,
   "gwh": 335.2
  },
  "id": "WRI1023233"
 },
 {
  "t": "RBB",
  "n": "RHE Bajina Basta",
  "c": "Hydro",
  "l": "Serbia",
  "mw": 614.0,
  "g": [
   43.9645,
   19.4102
  ],
  "y": null,
  "o": null,
  "src": "ENTSOE",
  "url": "https://transparency.entsoe.eu/generation/r2/installedCapacityPerProductionUnit/show",
  "gen": {
   "year": 2015,
   "gwh": 1.4
  },
  "id": "WRI1020281"
 },
 {
  "t": "KOMA",
  "n": "Koman",
  "c": "Hydro",
  "l": "Albania",
  "mw": 600.0,
  "g": [
   42.1033,
   19.8224
  ],
  "y": 1985,
  "o": null,
  "src": "Energy Charter Secretariat",
  "url": "http://www.energycharter.org/fileadmin/DocumentsMedia/IDEER/IDEER-Albania_2013_en.pdf",
  "gen": null,
  "id": "WRI1002171"
 },
 {
  "t": "PBA",
  "n": "Porąbka-Żar",
  "c": "Hydro",
  "l": "Poland",
  "mw": 540.0,
  "g": [
   49.7809,
   19.2115
  ],
  "y": 1979,
  "o": "Polska Grupa Energetyczna SA",
  "src": "ENTSOE",
  "url": "https://transparency.entsoe.eu/generation/r2/installedCapacityPerProductionUnit/show",
  "gen": {
   "year": 2017,
   "gwh": 184.1
  },
  "id": "WRI1019048"
 },
 {
  "t": "SAUC",
  "n": "Saucelle II 1",
  "c": "Hydro",
  "l": "Spain",
  "mw": 516.4,
  "g": [
   41.045,
   -6.8067
  ],
  "y": 1989,
  "o": "IBERDROLA GENERACION  S.A.",
  "src": "Red Eléctrica de España",
  "url": "http://www.ree.es/en/statistical-data-of-spanish-electrical-system/annual-report/preliminary-report-spanish-electricity-system-2015",
  "gen": {
   "year": 2017,
   "gwh": 23.3
  },
  "id": "WRI1007891"
 },
 {
  "t": "HL",
  "n": "HPP Lotru",
  "c": "Hydro",
  "l": "Romania",
  "mw": 509.0,
  "g": [
   45.4472,
   23.7683
  ],
  "y": null,
  "o": null,
  "src": "ENTSOE",
  "url": "https://transparency.entsoe.eu/generation/r2/installedCapacityPerProductionUnit/show",
  "gen": {
   "year": 2017,
   "gwh": 465.4
  },
  "id": "WRI1019100"
 },
 {
  "t": "KS",
  "n": "KW Silz",
  "c": "Hydro",
  "l": "Austria",
  "mw": 500.0,
  "g": [
   47.2696,
   10.9678
  ],
  "y": 1981,
  "o": "TIWAG-Tiroler Wasserkraft AG",
  "src": "Open Power System Data",
  "url": "http://data.open-power-system-data.org/",
  "gen": null,
  "id": "WRI1005914"
 },
 {
  "t": "FIER",
  "n": "Fierza",
  "c": "Hydro",
  "l": "Albania",
  "mw": 500.0,
  "g": [
   42.2514,
   20.0431
  ],
  "y": 1978,
  "o": null,
  "src": "Energy Charter Secretariat",
  "url": "http://www.energycharter.org/fileadmin/DocumentsMedia/IDEER/IDEER-Albania_2013_en.pdf",
  "gen": null,
  "id": "WRI1002170"
 },
 {
  "t": "MIRA",
  "n": "Miraah CSP",
  "c": "Solar",
  "l": "Oman",
  "mw": 1021.0,
  "g": [
   18.35,
   55.71
  ],
  "y": null,
  "o": null,
  "src": "Wiki-Solar",
  "url": "https://www.wiki-solar.org",
  "gen": null,
  "id": "WKS0066498"
 },
 {
  "t": "DT",
  "n": "Datong TopRunner",
  "c": "Solar",
  "l": "China",
  "mw": 1000.0,
  "g": [
   40.008,
   112.956
  ],
  "y": null,
  "o": null,
  "src": "Wiki-Solar",
  "url": "https://www.wiki-solar.org",
  "gen": null,
  "id": "WKS0073631"
 },
 {
  "t": "IKI",
  "n": "Ili Kazakh I",
  "c": "Solar",
  "l": "China",
  "mw": 1000.0,
  "g": [
   43.992,
   80.826
  ],
  "y": null,
  "o": null,
  "src": "Wiki-Solar",
  "url": "https://www.wiki-solar.org",
  "gen": null,
  "id": "WKS0063014"
 },
 {
  "t": "YANC",
  "n": "Yanchi",
  "c": "Solar",
  "l": "China",
  "mw": 1000.0,
  "g": [
   37.982,
   106.999
  ],
  "y": null,
  "o": null,
  "src": "Wiki-Solar",
  "url": "https://www.wiki-solar.org",
  "gen": null,
  "id": "WKS0069544"
 },
 {
  "t": "KSPP",
  "n": "Kamuthi Solar Power Plant",
  "c": "Solar",
  "l": "India",
  "mw": 648.0,
  "g": [
   9.3381,
   78.3917
  ],
  "y": null,
  "o": "Adani Power Limited",
  "src": "Adani Power Limite r Er",
  "url": "http://www.adanipower.com",
  "gen": null,
  "id": "WRI1026151"
 },
 {
  "t": "BHSP",
  "n": "BhSP3",
  "c": "Solar",
  "l": "India",
  "mw": 560.0,
  "g": [
   27.491,
   71.961
  ],
  "y": null,
  "o": null,
  "src": "Wiki-Solar",
  "url": "https://www.wiki-solar.org",
  "gen": null,
  "id": "WKS0069465"
 },
 {
  "t": "HRSF",
  "n": "Haughton River Solar Farm",
  "c": "Solar",
  "l": "Australia",
  "mw": 500.0,
  "g": [
   -19.733,
   147.0483
  ],
  "y": null,
  "o": "SPIC",
  "src": "Australian Renewable Energy Mapping Infrastructure",
  "url": "https://www.nationalmap.gov.au/",
  "gen": null,
  "id": "AUS0000592"
 },
 {
  "t": "KUMS",
  "n": "KUMSP Greenko",
  "c": "Solar",
  "l": "India",
  "mw": 500.0,
  "g": [
   15.679,
   78.274
  ],
  "y": null,
  "o": null,
  "src": "Wiki-Solar",
  "url": "https://www.wiki-solar.org",
  "gen": null,
  "id": "WKS0069391"
 },
 {
  "t": "DAU",
  "n": "Dau Tieng",
  "c": "Solar",
  "l": "Vietnam",
  "mw": 420.0,
  "g": [
   11.335,
   106.275
  ],
  "y": null,
  "o": null,
  "src": "Wiki-Solar",
  "url": "https://www.wiki-solar.org",
  "gen": null,
  "id": "WKS0072161"
 },
 {
  "t": "QEA",
  "n": "Quaid-e-Azam",
  "c": "Solar",
  "l": "Pakistan",
  "mw": 400.0,
  "g": [
   29.3178,
   71.824
  ],
  "y": 2015,
  "o": "Government of Punjab",
  "src": "Quaid-E-Azam Solar Power (Private) Ltd.",
  "url": "https://www.qasolar.com/downloads/outputs-progress-report-of-plant/",
  "gen": null,
  "id": "WRI1026464"
 },
 {
  "t": "VI",
  "n": "Villanueva I",
  "c": "Solar",
  "l": "Mexico",
  "mw": 330.0,
  "g": [
   25.586,
   -103.056
  ],
  "y": null,
  "o": null,
  "src": "Wiki-Solar",
  "url": "https://www.wiki-solar.org",
  "gen": null,
  "id": "WKS0067953"
 },
 {
  "t": "PCN",
  "n": "Phước Nam",
  "c": "Solar",
  "l": "Vietnam",
  "mw": 330.0,
  "g": [
   11.446,
   108.866
  ],
  "y": null,
  "o": null,
  "src": "Wiki-Solar",
  "url": "https://www.wiki-solar.org",
  "gen": null,
  "id": "WKS0071353"
 },
 {
  "t": "PL",
  "n": "Puerto Libertad",
  "c": "Solar",
  "l": "Mexico",
  "mw": 320.0,
  "g": [
   29.945,
   -112.665
  ],
  "y": null,
  "o": null,
  "src": "Wiki-Solar",
  "url": "https://www.wiki-solar.org",
  "gen": null,
  "id": "WKS0068685"
 },
 {
  "t": "CEST",
  "n": "Cestas",
  "c": "Solar",
  "l": "France",
  "mw": 301.4,
  "g": [
   44.7242,
   -0.815
  ],
  "y": null,
  "o": null,
  "src": "Open Power System Data",
  "url": "http://data.open-power-system-data.org/renewable_power_plants/2016-10-21/",
  "gen": null,
  "id": "WRI1023933"
 },
 {
  "t": "CAUC",
  "n": "Cauchari",
  "c": "Solar",
  "l": "Argentina",
  "mw": 300.0,
  "g": [
   -23.8,
   -66.8
  ],
  "y": null,
  "o": null,
  "src": "Wiki-Solar",
  "url": "https://www.wiki-solar.org",
  "gen": null,
  "id": "WKS0068701"
 },
 {
  "t": "MI",
  "n": "Mbrsp Iiib",
  "c": "Solar",
  "l": "United Arab Emirates",
  "mw": 300.0,
  "g": [
   24.765,
   55.37
  ],
  "y": null,
  "o": null,
  "src": "Wiki-Solar",
  "url": "https://www.wiki-solar.org",
  "gen": null,
  "id": "WKS0069244"
 },
 {
  "t": "SOLE",
  "n": "Solem",
  "c": "Solar",
  "l": "Mexico",
  "mw": 287.0,
  "g": [
   21.895,
   -102.082
  ],
  "y": null,
  "o": null,
  "src": "Wiki-Solar",
  "url": "https://www.wiki-solar.org",
  "gen": null,
  "id": "WKS0068684"
 },
 {
  "t": "VIL2",
  "n": "Villanueva III",
  "c": "Solar",
  "l": "Mexico",
  "mw": 250.0,
  "g": [
   25.577,
   -103.034
  ],
  "y": null,
  "o": null,
  "src": "Wiki-Solar",
  "url": "https://www.wiki-solar.org",
  "gen": null,
  "id": "WKS0067954"
 },
 {
  "t": "SETO",
  "n": "Setouchi",
  "c": "Solar",
  "l": "Japan",
  "mw": 230.0,
  "g": [
   34.643,
   134.159
  ],
  "y": null,
  "o": null,
  "src": "Wiki-Solar",
  "url": "https://www.wiki-solar.org",
  "gen": null,
  "id": "WKS0064086"
 },
 {
  "t": "CSPP",
  "n": "Charanka Solar Power Plant",
  "c": "Solar",
  "l": "India",
  "mw": 221.0,
  "g": [
   23.907,
   71.1881
  ],
  "y": null,
  "o": "Charanka Solar Park",
  "src": "Solar for India",
  "url": "https://natgrp.org/charanka-gujarat-solar-park/",
  "gen": null,
  "id": "WRI1026129"
 },
 {
  "t": "MBRS",
  "n": "Mbrsp II",
  "c": "Solar",
  "l": "United Arab Emirates",
  "mw": 220.0,
  "g": [
   24.759,
   55.383
  ],
  "y": null,
  "o": null,
  "src": "Wiki-Solar",
  "url": "https://www.wiki-solar.org",
  "gen": null,
  "id": "WKS0065024"
 },
 {
  "t": "SOL2",
  "n": "Solara4",
  "c": "Solar",
  "l": "Portugal",
  "mw": 218.8,
  "g": [
   37.365,
   -7.665
  ],
  "y": null,
  "o": null,
  "src": "Wiki-Solar",
  "url": "https://www.wiki-solar.org",
  "gen": null,
  "id": "WKS0070717"
 },
 {
  "t": "ITUV",
  "n": "Ituverava",
  "c": "Solar",
  "l": "Brazil",
  "mw": 210.0,
  "g": [
   -12.594,
   -44.112
  ],
  "y": null,
  "o": null,
  "src": "Wiki-Solar",
  "url": "https://www.wiki-solar.org",
  "gen": null,
  "id": "WKS0066301"
 },
 {
  "t": "NO",
  "n": "Nova Olinda",
  "c": "Solar",
  "l": "Brazil",
  "mw": 210.0,
  "g": [
   -8.213,
   -42.545
  ],
  "y": null,
  "o": null,
  "src": "Wiki-Solar",
  "url": "https://www.wiki-solar.org",
  "gen": null,
  "id": "WKS0066304"
 },
 {
  "t": "TB",
  "n": "Thuan Bac",
  "c": "Solar",
  "l": "Vietnam",
  "mw": 204.0,
  "g": [
   11.7,
   109.03
  ],
  "y": null,
  "o": null,
  "src": "Wiki-Solar",
  "url": "https://www.wiki-solar.org",
  "gen": null,
  "id": "WKS0072323"
 },
 {
  "t": "SOLA",
  "n": "Solaben 3",
  "c": "Solar",
  "l": "Spain",
  "mw": 200.0,
  "g": [
   39.226,
   -5.3905
  ],
  "y": 2012,
  "o": "SOLABEN ELECTRICIDAD TRES  S.A.",
  "src": "Red Eléctrica de España",
  "url": "http://www.ree.es/en/statistical-data-of-spanish-electrical-system/annual-report/preliminary-report-spanish-electricity-system-2015",
  "gen": null,
  "id": "WRI1007925"
 },
 {
  "t": "CENT",
  "n": "Centrale Solaire Noor Ouarzazate 2",
  "c": "Solar",
  "l": "Morocco",
  "mw": 200.0,
  "g": [
   31.0092,
   -6.8622
  ],
  "y": 2018,
  "o": null,
  "src": "National Renewable Energy Laboratory",
  "url": "https://www.nrel.gov/csp/solarpaces/project_detail.cfm/projectID=4292",
  "gen": null,
  "id": "WRI1061197"
 },
 {
  "t": "GOLM",
  "n": "Golmud",
  "c": "Solar",
  "l": "China",
  "mw": 200.0,
  "g": [
   36.4,
   95.157
  ],
  "y": null,
  "o": "Huanghe Hydropower Development Co.  Ltd.",
  "src": "UNFCCC CDM",
  "url": "http://cdm.unfccc.int/filestorage/2/l/UX0LSPT1K26IRFOYQ3JD8ENBZAWG7C.pdf/7162-%20PDD.pdf?t=THd8b2o5c3VhfDDPUJlbXbiqJNR-viiaqUp6",
  "gen": null,
  "id": "WRI1025948"
 },
 {
  "t": "SUNR",
  "n": "Sunraysia",
  "c": "Solar",
  "l": "Australia",
  "mw": 200.0,
  "g": [
   -34.804,
   143.491
  ],
  "y": null,
  "o": null,
  "src": "Wiki-Solar",
  "url": "https://www.wiki-solar.org",
  "gen": null,
  "id": "WKS0069205"
 },
 {
  "t": "IIIA",
  "n": "Mbrsp Iiia",
  "c": "Solar",
  "l": "United Arab Emirates",
  "mw": 200.0,
  "g": [
   24.747,
   55.385
  ],
  "y": null,
  "o": null,
  "src": "Wiki-Solar",
  "url": "https://www.wiki-solar.org",
  "gen": null,
  "id": "WKS0069243"
 },
 {
  "t": "ROME",
  "n": "El Romero",
  "c": "Solar",
  "l": "Chile",
  "mw": 196.0,
  "g": [
   -29.112,
   -70.915
  ],
  "y": null,
  "o": null,
  "src": "Wiki-Solar",
  "url": "https://www.wiki-solar.org",
  "gen": null,
  "id": "WKS0062353"
 },
 {
  "t": "HSF",
  "n": "Hayman Solar Farm",
  "c": "Solar",
  "l": "Australia",
  "mw": 180.0,
  "g": [
   -20.4877,
   147.7449
  ],
  "y": null,
  "o": "Edify Energy Blackrock",
  "src": "Australian Renewable Energy Mapping Infrastructure",
  "url": "https://www.nationalmap.gov.au/",
  "gen": null,
  "id": "AUS0000532"
 },
 {
  "t": "CSNO",
  "n": "Centrale Solaire Noor Ouarzazate 1",
  "c": "Solar",
  "l": "Morocco",
  "mw": 160.0,
  "g": [
   31.0404,
   -6.8449
  ],
  "y": 2016,
  "o": "Moroccan Agency for Renewable Energies (MASEN)",
  "src": "Arab Union of Electricity",
  "url": "http://www.auptde.org/NewsDetails.aspx?lang=en&NID=283",
  "gen": {
   "year": 2016,
   "gwh": 370.0
  },
  "id": "WRI1023680"
 },
 {
  "t": "PSTS",
  "n": "Planta Solar Termica Solnova 1",
  "c": "Solar",
  "l": "Spain",
  "mw": 150.0,
  "g": [
   37.4179,
   -6.2771
  ],
  "y": 2010,
  "o": "SOLNOVA ELECTRICIDAD S.A (A-91378992)",
  "src": "Red Eléctrica de España",
  "url": "http://www.ree.es/en/statistical-data-of-spanish-electrical-system/annual-report/preliminary-report-spanish-electricity-system-2015",
  "gen": null,
  "id": "WRI1023647"
 },
 {
  "t": "NOOR",
  "n": "Centrale Solaire Noor Ouarzazate 3",
  "c": "Solar",
  "l": "Morocco",
  "mw": 150.0,
  "g": [
   31.0092,
   -6.8622
  ],
  "y": 2017,
  "o": null,
  "src": "National Renewable Energy Laboratory",
  "url": "https://www.nrel.gov/csp/solarpaces/project_detail.cfm/projectID=4293",
  "gen": null,
  "id": "WRI1061198"
 },
 {
  "t": "HHN",
  "n": "Hornsea 1 - Heron & Njord",
  "c": "Wind",
  "l": "United Kingdom",
  "mw": 1200.0,
  "g": [
   53.6815,
   1.4207
  ],
  "y": null,
  "o": "Orsted (formerly Dong Energy)",
  "src": "UK Renewable Energy Planning Database",
  "url": "https://www.gov.uk/government/collections/renewable-energy-planning-data",
  "gen": null,
  "id": "GBR2001034"
 },
 {
  "t": "HHWE",
  "n": "Horse Hollow Wind Energy Center",
  "c": "Wind",
  "l": "United States of America",
  "mw": 735.5,
  "g": [
   32.214,
   -100.0571
  ],
  "y": 2006,
  "o": "FPL Energy Horse Hollow LLC",
  "src": "U.S. Energy Information Administration",
  "url": "http://www.eia.gov/electricity/data/browser/",
  "gen": {
   "year": 2019,
   "gwh": 2493.5
  },
  "id": "USA0056291"
 },
 {
  "t": "CRWL",
  "n": "Capricorn Ridge Wind LLC",
  "c": "Wind",
  "l": "United States of America",
  "mw": 662.5,
  "g": [
   31.952,
   -101.0189
  ],
  "y": 2007,
  "o": "Capricorn Ridge Wind LLC",
  "src": "U.S. Energy Information Administration",
  "url": "http://www.eia.gov/electricity/data/browser/",
  "gen": {
   "year": 2019,
   "gwh": 2237.5
  },
  "id": "USA0056763"
 },
 {
  "t": "WALN",
  "n": "Walney 3",
  "c": "Wind",
  "l": "United Kingdom",
  "mw": 660.0,
  "g": [
   54.09,
   -3.74
  ],
  "y": null,
  "o": "Orsted (formerly Dong Energy)",
  "src": "UK Renewable Energy Planning Database",
  "url": "https://www.gov.uk/government/collections/renewable-energy-planning-data",
  "gen": null,
  "id": "GBR2001036"
 },
 {
  "t": "LA",
  "n": "London Array",
  "c": "Wind",
  "l": "United Kingdom",
  "mw": 630.0,
  "g": [
   51.6217,
   1.4958
  ],
  "y": null,
  "o": "Siemens Gamesa Renewable Energy",
  "src": "UK Renewable Energy Planning Database",
  "url": "https://www.gov.uk/government/collections/renewable-energy-planning-data",
  "gen": null,
  "id": "GBR0002511"
 },
 {
  "t": "FRWF",
  "n": "Fowler Ridge Wind Farm LLC",
  "c": "Wind",
  "l": "United States of America",
  "mw": 600.3,
  "g": [
   40.5839,
   -87.3336
  ],
  "y": 2009,
  "o": "AE Power Services LLC",
  "src": "U.S. Energy Information Administration",
  "url": "http://www.eia.gov/electricity/data/browser/",
  "gen": {
   "year": 2019,
   "gwh": 1521.6
  },
  "id": "USA0056777"
 },
 {
  "t": "RCW",
  "n": "Rush Creek Wind",
  "c": "Wind",
  "l": "United States of America",
  "mw": 600.0,
  "g": [
   39.1721,
   -103.8454
  ],
  "y": 2019,
  "o": "Public Service Co of Colorado",
  "src": "U.S. Energy Information Administration",
  "url": "http://www.eia.gov/electricity/data/browser/",
  "gen": {
   "year": 2019,
   "gwh": 1975.1
  },
  "id": "USA0060619"
 },
 {
  "t": "GEMI",
  "n": "Gemini",
  "c": "Wind",
  "l": "Netherlands",
  "mw": 600.0,
  "g": [
   54.036,
   5.963
  ],
  "y": 2016,
  "o": null,
  "src": "Wind Stats Netherlands",
  "url": "https://web.archive.org/web/20170818030302/http://www.windstats.nl:80/turbines.php",
  "gen": {
   "year": 2016,
   "gwh": 2895.0
  },
  "id": "WRI1005330"
 },
 {
  "t": "BEAT",
  "n": "Beatrice",
  "c": "Wind",
  "l": "United Kingdom",
  "mw": 588.0,
  "g": [
   58.0882,
   -2.9502
  ],
  "y": null,
  "o": "Scottish & Southern Energy (SSE) / Repsol / CIP",
  "src": "UK Renewable Energy Planning Database",
  "url": "https://www.gov.uk/government/collections/renewable-energy-planning-data",
  "gen": null,
  "id": "GBR2001031"
 },
 {
  "t": "ZAFA",
  "n": "Zafarana",
  "c": "Wind",
  "l": "Egypt",
  "mw": 547.0,
  "g": [
   29.2392,
   32.5983
  ],
  "y": null,
  "o": null,
  "src": "Egyptian Electricity Holding Company",
  "url": "http://www.moee.gov.eg/english_new/report.aspx",
  "gen": {
   "year": 2014,
   "gwh": 1332.0
  },
  "id": "WRI1000087"
 },
 {
  "t": "MWWF",
  "n": "Murra Warra Wind Farm",
  "c": "Wind",
  "l": "Australia",
  "mw": 429.0,
  "g": [
   -36.4333,
   142.3182
  ],
  "y": null,
  "o": "RES Australia",
  "src": "Australian Renewable Energy Mapping Infrastructure",
  "url": "https://www.nationalmap.gov.au/",
  "gen": null,
  "id": "AUS0000610"
 },
 {
  "t": "MWF",
  "n": "Macarthur Wind Farm",
  "c": "Wind",
  "l": "Australia",
  "mw": 420.0,
  "g": [
   -38.0648,
   142.1844
  ],
  "y": null,
  "o": "AGL Energy Pty Ltd",
  "src": "Australian Renewable Energy Mapping Infrastructure",
  "url": "https://www.nationalmap.gov.au/",
  "gen": {
   "year": 2018,
   "gwh": 1047.5
  },
  "id": "AUS0000417"
 },
 {
  "t": "GTI",
  "n": "Global Tech I",
  "c": "Wind",
  "l": "Germany",
  "mw": 400.0,
  "g": [
   54.509,
   6.367
  ],
  "y": 2015,
  "o": "HEAG Südhessische Energie AG /   Stadtwerke München GmbH",
  "src": "Bundesnetzagentur",
  "url": "https://www.bundesnetzagentur.de/DE/Sachgebiete/ElektrizitaetundGas/Unternehmen_Institutionen/Versorgungssicherheit/Erzeugungskapazitaeten/Kraftwerksliste/kraftwerksliste-node.html",
  "gen": null,
  "id": "WRI1025865"
 },
 {
  "t": "ANHO",
  "n": "Anholt",
  "c": "Wind",
  "l": "Denmark",
  "mw": 399.6,
  "g": [
   56.603,
   11.209
  ],
  "y": 2013,
  "o": "50% Dong Energy",
  "src": "ENTSOE",
  "url": "https://transparency.entsoe.eu/generation/r2/installedCapacityPerProductionUnit/show",
  "gen": {
   "year": 2017,
   "gwh": 1881.0
  },
  "id": "WRI1022033"
 },
 {
  "t": "UB",
  "n": "UW Bertikow",
  "c": "Wind",
  "l": "Germany",
  "mw": 340.0,
  "g": [
   53.2641,
   14.048
  ],
  "y": 2003,
  "o": "ENERTRAG Aktiengesellschaft",
  "src": "Bundesnetzagentur",
  "url": "https://www.bundesnetzagentur.de/DE/Sachgebiete/ElektrizitaetundGas/Unternehmen_Institutionen/Versorgungssicherheit/Erzeugungskapazitaeten/Kraftwerksliste/kraftwerksliste-node.html",
  "gen": null,
  "id": "WRI1025851"
 },
 {
  "t": "BRI",
  "n": "Borkum Riffgrund I",
  "c": "Wind",
  "l": "Germany",
  "mw": 312.0,
  "g": [
   53.9667,
   6.55
  ],
  "y": 2015,
  "o": "Borkum Riffgrund I Offshore Windpark A/S GmbH & Co. oHG",
  "src": "Bundesnetzagentur",
  "url": "https://www.bundesnetzagentur.de/DE/Sachgebiete/ElektrizitaetundGas/Unternehmen_Institutionen/Versorgungssicherheit/Erzeugungskapazitaeten/Kraftwerksliste/kraftwerksliste-node.html",
  "gen": null,
  "id": "WRI1025854"
 },
 {
  "t": "LT",
  "n": "Lake Turkana",
  "c": "Wind",
  "l": "Kenya",
  "mw": 310.0,
  "g": [
   2.6447,
   36.7378
  ],
  "y": 2017,
  "o": "Lake Turkana Wind Power Ltd.",
  "src": "Lake Turkana Wind Power",
  "url": "http://ltwp.co.ke/",
  "gen": null,
  "id": "WRI1000054"
 },
 {
  "t": "PET",
  "n": "Parc Eolien Tarfaya",
  "c": "Wind",
  "l": "Morocco",
  "mw": 301.0,
  "g": [
   35.611,
   -5.432
  ],
  "y": 2014,
  "o": "Nareva Holding/Engie",
  "src": "Arab Union of Electricity",
  "url": "http://www.auptde.org/NewsDetails.aspx?lang=en&NID=283",
  "gen": null,
  "id": "WRI1023709"
 },
 {
  "t": "LAC",
  "n": "Lac-Alfred",
  "c": "Wind",
  "l": "Canada",
  "mw": 300.0,
  "g": [
   48.4194,
   -67.7137
  ],
  "y": null,
  "o": "Enbridge (67.5%) / EDF Energies Nouvelles (20%) / Mrc of La Mitis & Matapedia (12.5%)",
  "src": "Natural Resources Canada",
  "url": "http://ftp.maps.canada.ca/pub/nacei_cnaie/energy_infrastructure/PowerPlantsAllGE100MW_NorthAmerica_201708.xlsx",
  "gen": null,
  "id": "CAN0002178"
 },
 {
  "t": "BR",
  "n": "Blackspring Ridge",
  "c": "Wind",
  "l": "Canada",
  "mw": 298.8,
  "g": [
   50.1525,
   -112.8226
  ],
  "y": null,
  "o": "EDF/Enbridge",
  "src": "Natural Resources Canada",
  "url": "http://ftp.maps.canada.ca/pub/nacei_cnaie/energy_infrastructure/PowerPlantsAllGE100MW_NorthAmerica_201708.xlsx",
  "gen": null,
  "id": "CAN0002112"
 },
 {
  "t": "ONO",
  "n": "OWP Nordsee Ost",
  "c": "Wind",
  "l": "Germany",
  "mw": 295.2,
  "g": [
   54.445,
   7.683
  ],
  "y": 2014,
  "o": "RWE International S.E.",
  "src": "Bundesnetzagentur",
  "url": "https://www.bundesnetzagentur.de/DE/Sachgebiete/ElektrizitaetundGas/Unternehmen_Institutionen/Versorgungssicherheit/Erzeugungskapazitaeten/Kraftwerksliste/kraftwerksliste-node.html",
  "gen": null,
  "id": "WRI1025860"
 },
 {
  "t": "BJOR",
  "n": "Bjorkhojden",
  "c": "Wind",
  "l": "Sweden",
  "mw": 288.0,
  "g": [
   63.423,
   16.1473
  ],
  "y": null,
  "o": "100% Statkraft",
  "src": "Statkraft",
  "url": "http://www.statkraft.com/energy-sources/Power-plants/Sweden/bjorkhojden-wind-farm/",
  "gen": null,
  "id": "WRI1002039"
 },
 {
  "t": "KW",
  "n": "K2 Wind",
  "c": "Wind",
  "l": "Canada",
  "mw": 270.0,
  "g": [
   43.9373,
   -81.6399
  ],
  "y": null,
  "o": "K2 Wind Ontario LP",
  "src": "Natural Resources Canada",
  "url": "http://ftp.maps.canada.ca/pub/nacei_cnaie/energy_infrastructure/PowerPlantsAllGE100MW_NorthAmerica_201708.xlsx",
  "gen": null,
  "id": "CAN0002165"
 },
 {
  "t": "SK",
  "n": "South Kent",
  "c": "Wind",
  "l": "Canada",
  "mw": 270.0,
  "g": [
   42.3495,
   -82.1071
  ],
  "y": null,
  "o": "South Kent Wind LP",
  "src": "Natural Resources Canada",
  "url": "http://ftp.maps.canada.ca/pub/nacei_cnaie/energy_infrastructure/PowerPlantsAllGE100MW_NorthAmerica_201708.xlsx",
  "gen": null,
  "id": "CAN0002243"
 },
 {
  "t": "SWF",
  "n": "Sapphire Wind Farm",
  "c": "Wind",
  "l": "Australia",
  "mw": 270.0,
  "g": [
   -29.6997,
   151.4119
  ],
  "y": null,
  "o": "CWP Renewables",
  "src": "Australian Renewable Energy Mapping Infrastructure",
  "url": "https://www.nationalmap.gov.au/",
  "gen": null,
  "id": "AUS0000607"
 },
 {
  "t": "AD",
  "n": "Alto Douro",
  "c": "Wind",
  "l": "Portugal",
  "mw": 253.2,
  "g": [
   41.0696,
   -7.5769
  ],
  "y": 2010,
  "o": null,
  "src": "Energias Endogenas de Portugal",
  "url": "http://e2p.inegi.up.pt/index.asp",
  "gen": null,
  "id": "WRI1023275"
 },
 {
  "t": "WC",
  "n": "WPP Cogealac",
  "c": "Wind",
  "l": "Romania",
  "mw": 246.0,
  "g": [
   44.5903,
   28.5653
  ],
  "y": null,
  "o": null,
  "src": "ENTSOE",
  "url": "https://transparency.entsoe.eu/generation/r2/installedCapacityPerProductionUnit/show",
  "gen": null,
  "id": "WRI1019109"
 },
 {
  "t": "AMI",
  "n": "Alto Minho I",
  "c": "Wind",
  "l": "Portugal",
  "mw": 240.0,
  "g": [
   42.0154,
   -8.3456
  ],
  "y": 2008,
  "o": null,
  "src": "Energias Endogenas de Portugal",
  "url": "http://e2p.inegi.up.pt/index.asp",
  "gen": null,
  "id": "WRI1023276"
 },
 {
  "t": "NB",
  "n": "Northeast Binnendijks",
  "c": "Wind",
  "l": "Netherlands",
  "mw": 217.5,
  "g": [
   52.588,
   4.223
  ],
  "y": 2014,
  "o": null,
  "src": "Wind Stats Netherlands",
  "url": "https://web.archive.org/web/20170818030302/http://www.windstats.nl:80/turbines.php",
  "gen": {
   "year": 2016,
   "gwh": 524.7
  },
  "id": "WRI1005409"
 },
 {
  "t": "NORT",
  "n": "Northwind",
  "c": "Wind",
  "l": "Belgium",
  "mw": 216.0,
  "g": [
   51.6186,
   2.8998
  ],
  "y": 2013,
  "o": null,
  "src": "4C Offshore",
  "url": "http://www.4coffshore.com/windfarms/northwind-belgium-be02.html",
  "gen": {
   "year": 2017,
   "gwh": 1222.5
  },
  "id": "WRI1002260"
 },
 {
  "t": "WEST",
  "n": "Westereems",
  "c": "Wind",
  "l": "Netherlands",
  "mw": 213.3,
  "g": [
   53.4375,
   6.8613
  ],
  "y": 2009,
  "o": null,
  "src": "Wind Stats Netherlands",
  "url": "https://web.archive.org/web/20170818030302/http://www.windstats.nl:80/turbines.php",
  "gen": {
   "year": 2016,
   "gwh": 554.7
  },
  "id": "WRI1005474"
 },
 {
  "t": "HRB",
  "n": "Horns Rev B",
  "c": "Wind",
  "l": "Denmark",
  "mw": 209.3,
  "g": [
   55.6,
   7.5825
  ],
  "y": 2010,
  "o": null,
  "src": "ENTSOE",
  "url": "https://transparency.entsoe.eu/generation/r2/installedCapacityPerProductionUnit/show",
  "gen": null,
  "id": "WRI1022038"
 },
 {
  "t": "ROED",
  "n": "Roedsand 2",
  "c": "Wind",
  "l": "Denmark",
  "mw": 207.0,
  "g": [
   54.5228,
   11.5447
  ],
  "y": 2010,
  "o": null,
  "src": "ENTSOE",
  "url": "https://transparency.entsoe.eu/generation/r2/installedCapacityPerProductionUnit/show",
  "gen": {
   "year": 2017,
   "gwh": 830.8
  },
  "id": "WRI1022039"
 },
 {
  "t": "CWF",
  "n": "Collgar Wind Farm",
  "c": "Wind",
  "l": "Australia",
  "mw": 206.0,
  "g": [
   -31.5432,
   118.4566
  ],
  "y": null,
  "o": "UBS IIT/ REST",
  "src": "Australian Renewable Energy Mapping Infrastructure",
  "url": "https://www.nationalmap.gov.au/",
  "gen": {
   "year": 2018,
   "gwh": 715.5
  },
  "id": "AUS0000307"
 },
 {
  "t": "PEA",
  "n": "Parc Eolien Akhfenir",
  "c": "Wind",
  "l": "Morocco",
  "mw": 202.1,
  "g": [
   27.9538,
   -11.9975
  ],
  "y": 2016,
  "o": "Nareva Holding",
  "src": "Wiki Eolinne",
  "url": "https://eolienne.f4jr.org/parcs/akhfenir",
  "gen": null,
  "id": "WRI1023701"
 }
];
