/* Generated by scripts/build-register.py. Do not edit by hand.
 *
 * Source: Global Power Plant Database v1.3.0, World Resources Institute, CC BY 4.0 — https://datasets.wri.org/dataset/globalpowerplantdatabase
 */

const ATTRIBUTION = "Global Power Plant Database v1.3.0, World Resources Institute, CC BY 4.0 \u2014 https://datasets.wri.org/dataset/globalpowerplantdatabase";

const PLANTS = [
 {
  "t": "GEYS",
  "n": "Geysers",
  "c": "Geothermal",
  "l": "United States of America",
  "mw": 1163.0,
  "g": [
   38.777,
   -122.745
  ],
  "y": 1979,
  "o": "Geysers Power Co LLC",
  "src": "U.S. Energy Information Administration",
  "url": "http://www.eia.gov/electricity/data/browser/",
  "gen": {
   "year": 2019,
   "gwh": 4351.4
  },
  "id": "USA0000286"
 },
 {
  "t": "UL",
  "n": "Unified Leyte",
  "c": "Geothermal",
  "l": "Philippines",
  "mw": 610.2,
  "g": [
   11.1308,
   124.6553
  ],
  "y": null,
  "o": null,
  "src": "Philippines Department of Energy",
  "url": "https://www.doe.gov.ph/list-existing-power-plants",
  "gen": null,
  "id": "WRI1001943"
 },
 {
  "t": "CP",
  "n": "Cerro Prieto",
  "c": "Geothermal",
  "l": "Mexico",
  "mw": 570.0,
  "g": [
   32.3916,
   -115.2252
  ],
  "y": null,
  "o": "CFE",
  "src": "CFE-CENACE",
  "url": "http://base.energia.gob.mx/nacei/Archivos/3%20P%C3%A1gina%20Datos%20de%20Infraestructura/Ingl%C3%A9s/PowerPlantsAllGE100MW_NorthAmerica_201606.xlsx",
  "gen": null,
  "id": "MEX0001868"
 },
 {
  "t": "MAKB",
  "n": "Makban",
  "c": "Geothermal",
  "l": "Philippines",
  "mw": 442.8,
  "g": [
   14.0881,
   121.2264
  ],
  "y": null,
  "o": null,
  "src": "Philippines Department of Energy",
  "url": "https://www.doe.gov.ph/list-existing-power-plants",
  "gen": null,
  "id": "WRI1001888"
 },
 {
  "t": "HELL",
  "n": "Hellisheiði",
  "c": "Geothermal",
  "l": "Iceland",
  "mw": 213.0,
  "g": [
   64.0373,
   -21.4007
  ],
  "y": 2006,
  "o": "Orkuveita Reykjavíkur",
  "src": "Iceland Energy Portal",
  "url": "http://gilslaug.orkugardur.is/vefsja/orkuvefsja_en.html",
  "gen": null,
  "id": "WRI1002796"
 },
 {
  "t": "OI",
  "n": "Olkaria I",
  "c": "Geothermal",
  "l": "Kenya",
  "mw": 185.0,
  "g": [
   -0.8933,
   36.3086
  ],
  "y": 1981,
  "o": "Kenya Electric Generating Company",
  "src": "Kenya Electricity Generating Company",
  "url": "http://www.kengen.co.ke/?q=kengen-download",
  "gen": null,
  "id": "WRI1061218"
 },
 {
  "t": "WAIR",
  "n": "Wairakei",
  "c": "Geothermal",
  "l": "New Zealand",
  "mw": 132.0,
  "g": [
   -38.6266,
   176.1055
  ],
  "y": null,
  "o": "Contact Energy",
  "src": "Contact Energy",
  "url": "https://contact.co.nz/corporate/about/our-company/powerstations",
  "gen": null,
  "id": "WRI1000331"
 },
 {
  "t": "TG",
  "n": "Three Gorges Dam",
  "c": "Hydro",
  "l": "China",
  "mw": 22500.0,
  "g": [
   30.8235,
   111.0032
  ],
  "y": 2003,
  "o": null,
  "src": "China Three Gorges Corporation",
  "url": "http://www.ctgpc.com.cn/sx/sxgczds.php?mClassId=015004",
  "gen": null,
  "id": "WRI1000452"
 },
 {
  "t": "SBG",
  "n": "Simon Bolivar (Guri)",
  "c": "Hydro",
  "l": "Venezuela",
  "mw": 8851.0,
  "g": [
   7.7659,
   -62.9982
  ],
  "y": null,
  "o": null,
  "src": "Venezuela Electricity Sector",
  "url": "http://www.mppee.gob.ve/download/anuario_estad%C3%ADstico/Anuario_2013.pdf",
  "gen": {
   "year": 2013,
   "gwh": 50834.0
  },
  "id": "WRI1018677"
 },
 {
  "t": "TUCU",
  "n": "Tucuruí",
  "c": "Hydro",
  "l": "Brazil",
  "mw": 8535.0,
  "g": [
   -3.8322,
   -49.6522
  ],
  "y": 1984,
  "o": null,
  "src": "Agência Nacional de Energia Elétrica (Brazil)",
  "url": "http://www2.aneel.gov.br/aplicacoes/capacidadebrasil/capacidadebrasil.cfm",
  "gen": null,
  "id": "BRA0002889"
 },
 {
  "t": "IPB",
  "n": "Itaipu (Parte Brasileira)",
  "c": "Hydro",
  "l": "Brazil",
  "mw": 7000.0,
  "g": [
   -25.4269,
   -54.5931
  ],
  "y": 1989,
  "o": null,
  "src": "Agência Nacional de Energia Elétrica (Brazil)",
  "url": "http://www2.aneel.gov.br/aplicacoes/capacidadebrasil/capacidadebrasil.cfm",
  "gen": null,
  "id": "BRA0001161"
 },
 {
  "t": "GC",
  "n": "Grand Coulee",
  "c": "Hydro",
  "l": "United States of America",
  "mw": 6809.0,
  "g": [
   47.9575,
   -118.9773
  ],
  "y": 1967,
  "o": "U S Bureau of Reclamation",
  "src": "U.S. Energy Information Administration",
  "url": "http://www.eia.gov/electricity/data/browser/",
  "gen": {
   "year": 2019,
   "gwh": 16639.4
  },
  "id": "USA0006163"
 },
 {
  "t": "BC",
  "n": "Bath County",
  "c": "Hydro",
  "l": "United States of America",
  "mw": 2862.0,
  "g": [
   38.2089,
   -79.8
  ],
  "y": 1986,
  "o": "Virginia Electric & Power Co",
  "src": "U.S. Energy Information Administration",
  "url": "http://www.eia.gov/electricity/data/browser/",
  "gen": {
   "year": 2019,
   "gwh": -780.3
  },
  "id": "USA0006167"
 },
 {
  "t": "LONG",
  "n": "Longyangxia",
  "c": "Hydro",
  "l": "China",
  "mw": 1280.0,
  "g": [
   36.12,
   100.92
  ],
  "y": 1992,
  "o": null,
  "src": "Chinese National Committee on Large Dams",
  "url": "http://www.chincold.org.cn/dams/rootfiles/2010/07/20/1279253974093926-1279253974095162.pdf",
  "gen": null,
  "id": "WRI1000484"
 },
 {
  "t": "MC",
  "n": "Miraah CSP",
  "c": "Solar",
  "l": "Oman",
  "mw": 1021.0,
  "g": [
   18.35,
   55.71
  ],
  "y": null,
  "o": null,
  "src": "Wiki-Solar",
  "url": "https://www.wiki-solar.org",
  "gen": null,
  "id": "WKS0066498"
 },
 {
  "t": "KSPP",
  "n": "Kamuthi Solar Power Plant",
  "c": "Solar",
  "l": "India",
  "mw": 648.0,
  "g": [
   9.3381,
   78.3917
  ],
  "y": null,
  "o": "Adani Power Limited",
  "src": "Adani Power Limite r Er",
  "url": "http://www.adanipower.com",
  "gen": null,
  "id": "WRI1026151"
 },
 {
  "t": "BHSP",
  "n": "BhSP3",
  "c": "Solar",
  "l": "India",
  "mw": 560.0,
  "g": [
   27.491,
   71.961
  ],
  "y": null,
  "o": null,
  "src": "Wiki-Solar",
  "url": "https://www.wiki-solar.org",
  "gen": null,
  "id": "WKS0069465"
 },
 {
  "t": "HRSF",
  "n": "Haughton River Solar Farm",
  "c": "Solar",
  "l": "Australia",
  "mw": 500.0,
  "g": [
   -19.733,
   147.0483
  ],
  "y": null,
  "o": "SPIC",
  "src": "Australian Renewable Energy Mapping Infrastructure",
  "url": "https://www.nationalmap.gov.au/",
  "gen": null,
  "id": "AUS0000592"
 },
 {
  "t": "DT",
  "n": "Dau Tieng",
  "c": "Solar",
  "l": "Vietnam",
  "mw": 420.0,
  "g": [
   11.335,
   106.275
  ],
  "y": null,
  "o": null,
  "src": "Wiki-Solar",
  "url": "https://www.wiki-solar.org",
  "gen": null,
  "id": "WKS0072161"
 },
 {
  "t": "QEA",
  "n": "Quaid-e-Azam",
  "c": "Solar",
  "l": "Pakistan",
  "mw": 400.0,
  "g": [
   29.3178,
   71.824
  ],
  "y": 2015,
  "o": "Government of Punjab",
  "src": "Quaid-E-Azam Solar Power (Private) Ltd.",
  "url": "https://www.qasolar.com/downloads/outputs-progress-report-of-plant/",
  "gen": null,
  "id": "WRI1026464"
 },
 {
  "t": "CEST",
  "n": "Cestas",
  "c": "Solar",
  "l": "France",
  "mw": 301.4,
  "g": [
   44.7242,
   -0.815
  ],
  "y": null,
  "o": null,
  "src": "Open Power System Data",
  "url": "http://data.open-power-system-data.org/renewable_power_plants/2016-10-21/",
  "gen": null,
  "id": "WRI1023933"
 },
 {
  "t": "GWF",
  "n": "Gansu Wind Farm",
  "c": "Wind",
  "l": "China",
  "mw": 6000.0,
  "g": [
   40.6876,
   95.7329
  ],
  "y": null,
  "o": null,
  "src": "Sinovel",
  "url": "http://www.sinovel.com/english/content/?146.html",
  "gen": null,
  "id": "WRI1023878"
 },
 {
  "t": "HHN",
  "n": "Hornsea 1 - Heron & Njord",
  "c": "Wind",
  "l": "United Kingdom",
  "mw": 1200.0,
  "g": [
   53.6815,
   1.4207
  ],
  "y": null,
  "o": "Orsted (formerly Dong Energy)",
  "src": "UK Renewable Energy Planning Database",
  "url": "https://www.gov.uk/government/collections/renewable-energy-planning-data",
  "gen": null,
  "id": "GBR2001034"
 },
 {
  "t": "WALN",
  "n": "Walney 3",
  "c": "Wind",
  "l": "United Kingdom",
  "mw": 660.0,
  "g": [
   54.09,
   -3.74
  ],
  "y": null,
  "o": "Orsted (formerly Dong Energy)",
  "src": "UK Renewable Energy Planning Database",
  "url": "https://www.gov.uk/government/collections/renewable-energy-planning-data",
  "gen": null,
  "id": "GBR2001036"
 },
 {
  "t": "LA",
  "n": "London Array",
  "c": "Wind",
  "l": "United Kingdom",
  "mw": 630.0,
  "g": [
   51.6217,
   1.4958
  ],
  "y": null,
  "o": "Siemens Gamesa Renewable Energy",
  "src": "UK Renewable Energy Planning Database",
  "url": "https://www.gov.uk/government/collections/renewable-energy-planning-data",
  "gen": null,
  "id": "GBR0002511"
 },
 {
  "t": "ANHO",
  "n": "Anholt",
  "c": "Wind",
  "l": "Denmark",
  "mw": 399.6,
  "g": [
   56.603,
   11.209
  ],
  "y": 2013,
  "o": "50% Dong Energy",
  "src": "ENTSOE",
  "url": "https://transparency.entsoe.eu/generation/r2/installedCapacityPerProductionUnit/show",
  "gen": {
   "year": 2017,
   "gwh": 1881.0
  },
  "id": "WRI1022033"
 },
 {
  "t": "WHIT",
  "n": "Whitelee",
  "c": "Wind",
  "l": "United Kingdom",
  "mw": 322.0,
  "g": [
   55.6812,
   -4.2791
  ],
  "y": null,
  "o": "CRE Energy/ Scottish Power",
  "src": "UK Renewable Energy Planning Database",
  "url": "https://www.gov.uk/government/collections/renewable-energy-planning-data",
  "gen": null,
  "id": "GBR0003489"
 },
 {
  "t": "LAC",
  "n": "Lac-Alfred",
  "c": "Wind",
  "l": "Canada",
  "mw": 300.0,
  "g": [
   48.4194,
   -67.7137
  ],
  "y": null,
  "o": "Enbridge (67.5%) / EDF Energies Nouvelles (20%) / Mrc of La Mitis & Matapedia (12.5%)",
  "src": "Natural Resources Canada",
  "url": "http://ftp.maps.canada.ca/pub/nacei_cnaie/energy_infrastructure/PowerPlantsAllGE100MW_NorthAmerica_201708.xlsx",
  "gen": null,
  "id": "CAN0002178"
 }
];
