/* Builds photos.js from whatever is in media/sources/.
 *
 * A source's photo is a file named after its ticker: media/sources/MEAD.jpg.
 * This walks that folder and writes the map the pages read, so a missing photo
 * is never a broken request: the pages only ask for files that are here.
 *
 *   node scripts/photos.js
 */
const fs = require("fs");
const path = require("path");

const DIR = path.join(__dirname, "..", "media", "sources");
const OUT = path.join(__dirname, "..", "photos.js");
const OK = new Set([".jpg", ".jpeg", ".png", ".webp", ".avif", ".svg"]);

const files = fs.existsSync(DIR) ? fs.readdirSync(DIR) : [];
const photos = {};
for (const f of files.sort()) {
  const ext = path.extname(f).toLowerCase();
  if (!OK.has(ext)) continue;
  const ticker = path.basename(f, ext).toUpperCase();
  photos[ticker] = `media/sources/${f}`;
}

/* Credits live beside the photos, one "TICKER: who took it, licence" per line. */
const creditsFile = path.join(DIR, "CREDITS.txt");
const credits = {};
if (fs.existsSync(creditsFile)) {
  for (const line of fs.readFileSync(creditsFile, "utf8").split("\n")) {
    const m = line.match(/^\s*([A-Z0-9]+)\s*:\s*(.+?)\s*$/);
    if (m) credits[m[1]] = m[2];
  }
}

fs.writeFileSync(OUT,
  `/* Generated by scripts/photos.js. Drop a file in media/sources/ named after a\n` +
  ` * source's ticker and run the script again.\n */\n\n` +
  `const PHOTOS = ${JSON.stringify(photos, null, 2)};\n\n` +
  `const PHOTO_CREDITS = ${JSON.stringify(credits, null, 2)};\n`);

console.log(`photos.js: ${Object.keys(photos).length} photo${Object.keys(photos).length === 1 ? "" : "s"}, ${Object.keys(credits).length} credited`);
