/* LilyPad en español. Claves = el texto en inglés tal cual está en el HTML (espacios normalizados). */
window.LILYPAD_ES = {
  // navegación y pie
  'Pairs': 'Pares', 'How it works': 'Cómo funciona', 'Stocks': 'Acciones', 'My playground': 'Mi zona', 'FAQ': 'FAQ', 'Docs': 'Docs',
  'Connect wallet': 'Conectar wallet', 'Launch a coin': 'Lanzar una coin', 'The pairs': 'Los pares', 'Launch a pair': 'Lanzar un par',
  'Questions': 'Preguntas', 'Live feed': 'En directo', 'Night on the pond': 'Noche en el estanque', 'A little pair. A big leap.': 'Un par pequeño. Un gran salto.',
  'Demo data · not connected': 'Datos de demo · sin conectar',
  // hero
  'LilyPad · every coin gets a pad on a stock': 'LilyPad · cada coin tiene su nenúfar en una acción',
  'Coins paired<br>with stocks': 'Coins emparejadas<br>con acciones',
  'Your next big idea. Priced in <em data-hero-stock-name>NVIDIA</em>.': 'Tu próxima gran idea. Cotizada en <em data-hero-stock-name>NVIDIA</em>.',
  'Launch a pair <i>↗</i>': 'Lanzar un par <i>↗</i>', 'Explore the pairs &nbsp;→': 'Ver los pares &nbsp;→', '✦&nbsp; Grab a frog. It hops.': '✦&nbsp; Coge una rana. Salta.', 'Scroll to explore &nbsp;↓': 'Baja para explorar &nbsp;↓',
  'Pause motion': 'Pausar', 'Reset': 'Reiniciar', 'Grab a frog. It hops.': 'Coge una rana. Salta.', 'Scroll to explore': 'Baja para explorar',
  // puente
  'Why a pad': 'Por qué un nenúfar',
  'A coin can start with a joke.<br>Its price can start with <em>a stock people already watch</em>.': 'Una coin puede empezar como una broma.<br>Su precio puede empezar con <em>una acción que la gente ya mira</em>.',
  // pares
  'Good things come in pairs': 'Las cosas buenas vienen en pares', 'Pick a pair.': 'Elige un par.',
  'Big ideas come in all shapes. Every pair here is on chain, quoted in the stock its frog wears.': 'Las grandes ideas tienen todas las formas. Cada par está en cadena, cotizado en la acción que lleva su rana.',
  'Make your own ↗': 'Crea el tuyo ↗', 'All pairs →': 'Todos los pares →', 'On the board': 'En el tablón',
  // cómo funciona
  'Pick a frog. Name your coin. Put them on a pad.': 'Elige una rana. Ponle nombre a tu coin. Súbelas al nenúfar.',
  'Every stock on the pond is a frog. Your coin rides on one of them: it is priced in that stock and bought and sold with it, on a curve that opens the moment the launch lands and hands over to a Uniswap v4 pool once it has raised enough. Three steps, one launch.': 'Cada acción del estanque es una rana. Tu coin va montada en una de ellas: se cotiza en esa acción y se compra y se vende con ella, en una curva que se abre en cuanto aterriza el lanzamiento y pasa a un pool de Uniswap v4 cuando ha recaudado lo suficiente. Tres pasos, un lanzamiento.',
  'Step 1': 'Paso 1', 'Step 2': 'Paso 2', 'Step 3': 'Paso 3',
  'Pick the stock': 'Elige la acción',
  'Choose the frog your coin will ride: NVIDIA, Tesla, Apple, the S&amp;P 500 and the rest. From that moment your coin is quoted in that share, not in ETH.': 'Elige la rana que llevará tu coin: NVIDIA, Tesla, Apple, el S&amp;P 500 y el resto. Desde ese momento tu coin se cotiza en esa acción, no en ETH.',
  'Name your coin': 'Ponle nombre',
  'A name, a ticker, a picture and a line about it. One billion supply, minted once by the factory into the curve. Buy first if you want to be the first holder.': 'Un nombre, un ticker, una imagen y una línea. Mil millones de supply, emitidos una sola vez por la fábrica dentro de la curva. Compra primero si quieres ser el primer holder.',
  'Launch and trade': 'Lanza y opera',
  'Your signature deploys the coin and opens its curve, quoted in the stock. Every buy pays stock into the curve; when it holds the graduation threshold, the curve seeds a Uniswap v4 pool with what it raised and closes. Your pair is on the board the same second.': 'Tu firma despliega la coin y abre su curva, cotizada en la acción. Cada compra mete acción en la curva; cuando alcanza el umbral de graduación, la curva crea un pool de Uniswap v4 con lo recaudado y se cierra. Tu par está en el tablón en el mismo segundo.',
  // por qué una acción
  'Why pair with a stock': 'Por qué emparejar con una acción',
  'A price you can reason about, a story that writes itself.': 'Un precio que se puede razonar, una historia que se escribe sola.',
  'ETH pairs make every new coin a leveraged bet on ETH. Pairing with a stock swaps that beta for something people already follow.': 'Los pares en ETH convierten cada coin nueva en una apuesta apalancada a ETH. Emparejar con una acción cambia esa beta por algo que la gente ya sigue.',
  'The narrative is built in': 'La narrativa viene de serie',
  'A coin paired with TSLA is a Tesla coin the moment it exists. Earnings, launches, headlines: the stock brings the attention, your token rides it.': 'Una coin emparejada con TSLA es una coin de Tesla desde que existe. Resultados, lanzamientos, titulares: la acción trae la atención y tu token la aprovecha.',
  'Quoted in a unit people know': 'Cotizada en una unidad que la gente conoce',
  'Prices read as fractions of a share, not of a gas token. Holders can tell in a glance whether the coin moved or the whole market did.': 'Los precios se leen como fracciones de una acción, no de un token de gas. Los holders ven de un vistazo si se movió la coin o todo el mercado.',
  'A graduation you can see': 'Una graduación que se puede ver',
  'The curve is public math: price, reserves and the graduation threshold are on chain for every pair. When enough of the stock is in, the Uniswap v4 pool is created automatically. Nobody decides when, and nobody holds keys to it.': 'La curva es matemática pública: precio, reservas y umbral de graduación están en cadena para cada par. Cuando entra suficiente acción, el pool de Uniswap v4 se crea solo. Nadie decide cuándo y nadie tiene sus llaves.',
  // verificar
  'Verify it yourself': 'Compruébalo tú mismo', 'What holds without trusting us.': 'Lo que se sostiene sin fiarse de nosotros.',
  'Everything a careful buyer checks before the first trade, answered on chain and linked here.': 'Todo lo que un comprador cuidadoso mira antes del primer trade, respondido en cadena y enlazado aquí.',
  'Priced and settled in the stock': 'Cotizado y liquidado en la acción',
  "The curve's quote asset is the stock token itself. There is no ETH leg: buys pay stock in, sells take stock out.": 'El activo de cotización de la curva es el propio token de la acción. No hay tramo en ETH: las compras meten acción, las ventas la sacan.',
  'Fixed supply, minted once': 'Supply fijo, emitido una vez',
  'One billion tokens, minted by the factory into the curve at launch. No owner is left who could mint more.': 'Mil millones de tokens, emitidos por la fábrica dentro de la curva al lanzar. No queda ningún dueño que pueda emitir más.',
  'Graduation is automatic': 'La graduación es automática',
  'When the curve holds its threshold of the stock, it seeds a Uniswap v4 pool and closes. The threshold is set per stock by the factory and shown on every pair.': 'Cuando la curva alcanza su umbral de acción, crea un pool de Uniswap v4 y se cierra. El umbral lo fija la fábrica por acción y se muestra en cada par.',
  'Open, verified factory': 'Fábrica abierta y verificada',
  'Every pair is launched through the public Pons V2 factory on Robinhood Chain, verified on the explorer. LilyPad puts no contract of its own in between, except the published launcher that bundles your first buy. <a data-cfg-href="factoryUrl" href="#">Factory contract ↗</a>': 'Cada par se lanza a través de la fábrica pública Pons V2 en Robinhood Chain, verificada en el explorador. LilyPad no pone ningún contrato propio en medio, salvo el lanzador publicado que agrupa tu primera compra. <a data-cfg-href="factoryUrl" href="#">Contrato de la fábrica ↗</a>',
  'Protocol': 'Protocolo', 'Chain': 'Cadena', 'Factory': 'Fábrica', 'Creation fee': 'Comisión de creación', 'Curve fee': 'Comisión de la curva', 'Creator tax': 'Impuesto del creador', 'After graduation': 'Tras la graduación', 'copy': 'copiar',
  // antes de operar
  'Before you trade': 'Antes de operar', 'What a coin on a pad is, and is not': 'Lo que es una coin en un nenúfar, y lo que no',
  'Four things worth reading before any transaction. None of them are hidden in a footer, and none of them change once a pair is open.': 'Cuatro cosas que merece la pena leer antes de cualquier transacción. Ninguna está escondida en un pie de página y ninguna cambia una vez abierto el par.',
  'It is not a share.': 'No es una acción.',
  'A coin paired with NVDA is priced in NVDA and trades against it. It does not give you NVIDIA stock, dividends or votes. The stock is what the curve holds, nothing more.': 'Una coin emparejada con NVDA se cotiza en NVDA y se opera contra ella. No te da acciones de NVIDIA, ni dividendos, ni votos. La acción es lo que guarda la curva, nada más.',
  'The stock is permanent.': 'La acción es permanente.',
  'A pair cannot be re-paired after launch. Pick the stock your buyers actually follow, because that decision outlives every other one you make.': 'Un par no se puede volver a emparejar después del lanzamiento. Elige la acción que tus compradores siguen de verdad, porque esa decisión sobrevive a todas las demás.',
  'A curve is not a market.': 'Una curva no es un mercado.',
  'Until it graduates, the only counterparty is the curve: every buy moves the price up and every sell moves it down, by formula. Buys in the first minutes also pay a snipe tax. Treat the price as a live reading, not a forecast.': 'Hasta que se gradúa, la única contraparte es la curva: cada compra sube el precio y cada venta lo baja, por fórmula. Las compras de los primeros minutos pagan además un impuesto anti-snipe. Trata el precio como una lectura en vivo, no como una previsión.',
  'Stock tokens are not for everyone.': 'Los stock tokens no son para todo el mundo.',
  "Robinhood's stock tokens are issued for eligible customers in the European Union and are geo-restricted. If you cannot hold the stock token, you cannot buy the coin. Check your local rules before anything else.": 'Los stock tokens de Robinhood se emiten para clientes elegibles de la Unión Europea y tienen restricción geográfica. Si no puedes tener el stock token, no puedes comprar la coin. Mira las normas de tu país antes que nada.',
  // preguntas
  'A few things you might wonder': 'Algunas dudas habituales', 'Questions': 'Preguntas',
  'What is a pair here?': '¿Qué es un par aquí?',
  "A coin and the stock it is priced in. You pick the stock at launch; the coin's curve is quoted in that stock and every trade settles in it, with no ETH in between.": 'Una coin y la acción en la que se cotiza. Eliges la acción al lanzar; la curva de la coin se cotiza en esa acción y cada trade se liquida en ella, sin ETH de por medio.',
  'Do I need to own the stock to launch?': '¿Necesito tener la acción para lanzar?',
  "No. Launching costs the factory's creation fee in ETH. You only need the stock token if you want a first buy. The curve starts with the full supply on the coin side; the stock side fills as people buy.": 'No. Lanzar cuesta la comisión de creación de la fábrica, en ETH. Solo necesitas el stock token si quieres hacer una primera compra. La curva empieza con todo el supply en el lado de la coin; el lado de la acción se llena según compra la gente.',
  'What happens to the stock people pay in?': '¿Qué pasa con la acción que paga la gente?',
  'It sits in the curve, and sells are paid out of it. When the curve reaches its graduation threshold, that stock and the remaining coins seed a Uniswap v4 pool automatically. There is no withdraw function, for the creator or for us.': 'Se queda en la curva, y las ventas se pagan de ahí. Cuando la curva alcanza su umbral de graduación, esa acción y las coins restantes crean un pool de Uniswap v4 automáticamente. No hay función de retirada, ni para el creador ni para nosotros.',
  'What do creators earn?': '¿Qué ganan los creadores?',
  "Whatever creator tax the launch sets on curve trades, up to the factory's maximum, claimable from the fee escrow. LilyPad launches default to 0%; the figure for each pair is on its page.": 'El impuesto de creador que fije el lanzamiento sobre los trades de la curva, hasta el máximo de la fábrica, reclamable desde el escrow de comisiones. Los lanzamientos de LilyPad usan 0% por defecto; la cifra de cada par está en su página.',
  'What happens when the stock market is closed?': '¿Qué pasa cuando la bolsa está cerrada?',
  'Tokenized stocks trade on chain around the clock; their price follows the underlying and can drift while the market is shut. Your pair keeps trading, quoted in that token, at whatever the pool says.': 'Las acciones tokenizadas se operan en cadena las 24 horas; su precio sigue al subyacente y puede desviarse mientras el mercado está cerrado. Tu par sigue operando, cotizado en ese token, al precio que diga la curva.',
  'Is any of this real?': '¿Algo de esto es real?',
  '<span data-demo>The pairs on this site are sample data until the adapter is wired to the chain. </span>LilyPad does not issue stocks or run the curves; it is a front end for the public Pons V2 factory on <span data-cfg="chain">—</span>, which pairs coins you create with tokenized shares issued by third parties. Read the docs and your local rules before launching or trading.': '<span data-demo>Los pares de este sitio son datos de muestra hasta que el adaptador esté conectado a la cadena. </span>LilyPad no emite acciones ni gestiona las curvas; es una interfaz para la fábrica pública Pons V2 en <span data-cfg="chain">—</span>, que empareja las coins que creas con acciones tokenizadas emitidas por terceros. Lee los docs y las normas de tu país antes de lanzar u operar.',
  'Protocol facts · what a pair is made of': 'Datos del protocolo · de qué está hecho un par',
  'Every pair is one coin and one curve, created in the same transaction. These rules are the same for every pair and do not change after launch.': 'Cada par es una coin y una curva, creadas en la misma transacción. Estas reglas son iguales para todos los pares y no cambian después del lanzamiento.',
  'Supply': 'Supply', 'Curve': 'Curva', 'Quoted in the stock · graduates to Uniswap v4': 'Cotizada en la acción · se gradúa a Uniswap v4', '1,000,000,000 · minted once': '1.000.000.000 · emitido una vez',
  // cabeceras de otras páginas
  'Every pair, quoted in its stock.': 'Cada par, cotizado en su acción.',
  "Prices are shares per token. The USD figure next to each one is the reference at the stock's last on-chain price.": 'Los precios son acciones por token. La cifra en USD de al lado es la referencia al último precio en cadena de la acción.',
  'Pair a new coin with a stock.': 'Empareja una coin nueva con una acción.',
  'Every stock a coin can sit on.': 'Todas las acciones sobre las que puede sentarse una coin.',
  'Tokenized shares issued on Robinhood Chain. Pick one to see its pairs, or launch straight onto it.': 'Acciones tokenizadas emitidas en Robinhood Chain. Elige una para ver sus pares o lanza directamente sobre ella.',
  'Your pairs, your positions.': 'Tus pares, tus posiciones.',
  'Everything you launched and everything you hold, in one place.': 'Todo lo que lanzaste y todo lo que tienes, en un solo sitio.',
  'Coin name': 'Nombre de la coin', 'Ticker': 'Ticker', 'Stock': 'Acción', 'Your first buy': 'Tu primera compra',
  'Up to 40 characters. This is what people will read on the board.': 'Hasta 40 caracteres. Es lo que la gente leerá en el tablón.',
  'Letters and numbers, 2 to 8.': 'Letras y números, de 2 a 8.',
  'Chosen once, at launch, and held for the life of the pair.': 'Se elige una vez, al lanzar, y se mantiene toda la vida del par.',
  'Launch the pair ↗': 'Lanzar el par ↗', 'Launch summary': 'Resumen del lanzamiento', 'Your coin': 'Tu coin',
  'All': 'Todos', 'New': 'Nuevos', 'Trending': 'Tendencia', 'Top': 'Top', 'All stocks': 'Todas las acciones',
  'Buy': 'Comprar', 'Sell': 'Vender', 'You pay': 'Pagas', 'You receive': 'Recibes', 'Price': 'Precio', 'Price impact': 'Impacto en el precio', 'Trades': 'Trades',
};
