/* Compiles TwistrCoin.sol into the file the page ships.
 *
 * Run it when the contract changes:  node contract/build.js
 * Needs solc on the machine; it is not a dependency of the site, which ships
 * the generated file and nothing else.
 *
 * evmVersion is pinned to paris on purpose. Shanghai and later emit PUSH0,
 * which is not accepted on every chain a token might be deployed to, and the
 * saving is a handful of gas.
 */
const fs = require('fs');
const path = require('path');
const solc = require('solc');

const SRC = path.join(__dirname, 'TwistrCoin.sol');
const OUT = path.join(__dirname, 'twistr-coin.js');

const out = JSON.parse(solc.compile(JSON.stringify({
  language: 'Solidity',
  sources: { 'TwistrCoin.sol': { content: fs.readFileSync(SRC, 'utf8') } },
  settings: {
    optimizer: { enabled: true, runs: 200 },
    evmVersion: 'paris',
    outputSelection: { '*': { '*': ['abi', 'evm.bytecode.object'] } },
  },
})));

const errors = (out.errors || []).filter((e) => e.severity === 'error');
if (errors.length) {
  errors.forEach((e) => console.error(e.formattedMessage));
  process.exit(1);
}

const c = out.contracts['TwistrCoin.sol'].TwistrCoin;
const bytecode = '0x' + c.evm.bytecode.object;

fs.writeFileSync(OUT, `/* Generated by contract/build.js — do not edit.
 * Source: contract/TwistrCoin.sol, solc ${solc.version()}, optimizer 200 runs, evmVersion paris.
 */
window.TWISTR_COIN = {
  version: ${JSON.stringify(solc.version())},
  bytecode: ${JSON.stringify(bytecode)},
  abi: ${JSON.stringify(c.abi)},
};
`);

console.log('wrote ' + path.relative(process.cwd(), OUT) + ' — ' + (bytecode.length - 2) / 2 + ' bytes of creation code');
