/* Compiles TwistrCoin.sol and TwistrFactory.sol into the files the page ships.
 *
 * Run it when the contract changes:  node contract/build.js
 * Needs solc on the machine; it is not a dependency of the site, which ships
 * the generated file and nothing else.
 *
 * evmVersion is pinned to paris on purpose. Shanghai and later emit PUSH0,
 * which is not accepted on every chain a token might be deployed to, and the
 * saving is a handful of gas.
 */
const fs = require('fs');
const path = require('path');
const solc = require('solc');

const SRC = path.join(__dirname, 'TwistrCoin.sol');
const FSRC = path.join(__dirname, 'TwistrFactory.sol');
const OUT = path.join(__dirname, 'twistr-coin.js');
const FOUT = path.join(__dirname, 'twistr-factory.js');

/* Both in one compilation unit: the factory imports the coin, so compiling
   them separately would mean solc resolving the import twice and no guarantee
   the coin the factory embeds is the coin the page deploys directly. */
const out = JSON.parse(solc.compile(JSON.stringify({
  language: 'Solidity',
  sources: {
    'TwistrCoin.sol': { content: fs.readFileSync(SRC, 'utf8') },
    'TwistrFactory.sol': { content: fs.readFileSync(FSRC, 'utf8') },
  },
  settings: {
    optimizer: { enabled: true, runs: 200 },
    /* The factory passes seven calldata strings straight into a constructor
       that takes eight arguments, and the legacy pipeline runs out of stack
       doing it. viaIR is the documented answer and it keeps the ABI flat —
       the alternative was wrapping the arguments in a struct, which would
       have pushed tuple encoding into chain.js for no benefit to anyone
       reading the contract. */
    viaIR: true,
    evmVersion: 'paris',
    outputSelection: { '*': { '*': ['abi', 'evm.bytecode.object', 'evm.deployedBytecode.object'] } },
  },
})));

const errors = (out.errors || []).filter((e) => e.severity === 'error');
if (errors.length) {
  errors.forEach((e) => console.error(e.formattedMessage));
  process.exit(1);
}

const c = out.contracts['TwistrCoin.sol'].TwistrCoin;
const bytecode = '0x' + c.evm.bytecode.object;

fs.writeFileSync(OUT, `/* Generated by contract/build.js — do not edit.
 * Source: contract/TwistrCoin.sol, solc ${solc.version()}, optimizer 200 runs, evmVersion paris.
 */
window.TWISTR_COIN = {
  version: ${JSON.stringify(solc.version())},
  bytecode: ${JSON.stringify(bytecode)},
  abi: ${JSON.stringify(c.abi)},
};
`);

console.log('wrote ' + path.relative(process.cwd(), OUT) + ' — ' + (bytecode.length - 2) / 2 + ' bytes of creation code');

const f = out.contracts['TwistrFactory.sol'].TwistrFactory;
const fbytecode = '0x' + f.evm.bytecode.object;

fs.writeFileSync(FOUT, `/* Generated by contract/build.js — do not edit.
 * Source: contract/TwistrFactory.sol, solc ${solc.version()}, optimizer 200 runs, evmVersion paris.
 *
 * The factory is deployed ONCE, by whoever runs the pad, and its address goes
 * in config.js. The bytecode is here so that deployment can be done from the
 * same build everything else was checked against, rather than pasted from
 * somewhere.
 */
window.TWISTR_FACTORY = {
  version: ${JSON.stringify(solc.version())},
  bytecode: ${JSON.stringify(fbytecode)},
  /* The RUNTIME code, which is what eth_getCode returns for a deployed
   * contract — not the creation code above, which includes the constructor and
   * is never stored on chain. This is here so the pad can check that the
   * address it is about to launch through really holds THIS factory. */
  deployedBytecode: ${JSON.stringify('0x' + f.evm.deployedBytecode.object)},
  abi: ${JSON.stringify(f.abi)},
};
`);

console.log('wrote ' + path.relative(process.cwd(), FOUT) + ' — ' + (fbytecode.length - 2) / 2 + ' bytes of creation code');
