#!/usr/bin/env node
/* Copies the flag of each fiat currency's country (flag-icons, MIT, square versions)
 * into web/public/flags and writes web/src/data/flags.ts, which maps currency codes to
 * those files. Crypto and metals get their own marks in the site, not flags.
 *
 *   node scripts/build-flags.mjs
 */
import { copyFileSync, existsSync, readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const require = createRequire(import.meta.url);
const flagsDir = join(dirname(require.resolve('flag-icons/package.json')), 'flags/1x1');
const currencies = JSON.parse(readFileSync(join(root, 'shared/currencies.json'), 'utf8'));

// currencies whose code does not start with their country's code
const SPECIAL = { EUR: 'eu', XCD: 'kn', XCG: 'cw', XOF: 'sn', XAF: 'cm', XPF: 'pf' };
const map = {};
const missing = [];
for (const c of currencies) {
  if (c.kind !== 'fiat') continue;
  const cc = SPECIAL[c.code] ?? c.code.slice(0, 2).toLowerCase();
  const src = join(flagsDir, `${cc}.svg`);
  if (!existsSync(src)) {
    missing.push(c.code);
    continue;
  }
  copyFileSync(src, join(root, 'web/public/flags', `${cc}.svg`));
  map[c.code] = cc;
}
copyFileSync(join(dirname(flagsDir), '..', 'LICENSE'), join(root, 'web/public/flags/LICENSE.txt'));
writeFileSync(
  join(root, 'web/src/data/flags.ts'),
  `/* Generated by scripts/build-flags.mjs: currency code -> flag file in /flags (flag-icons, MIT). */
export const FLAGS: Record<string, string> = ${JSON.stringify(map, null, 2).replace(/"([A-Z]{3})":/g, '$1:').replace(/"/g, "'")};
`,
);
console.log(`${Object.keys(map).length} flags${missing.length ? `; no flag for ${missing.join(', ')}` : ''}`);
