#!/usr/bin/env node
/* Rasterizes the world's coastlines (Natural Earth 1:50m land, public domain, via the
 * world-atlas package) into a small equirectangular land mask for the planet in the
 * sky, and writes it to web/src/storm/earthMask.ts.
 *
 *   node scripts/build-earth.mjs [--preview out.png]
 *
 * The mask is W x H pixels, row 0 at latitude +90, column 0 at longitude -180, 1 for
 * land. Each row is stored as alternating run lengths (sea first), as LEB128 varints,
 * base64-encoded. The site adds the fractal detail, colours and clouds on the GPU. */
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { deflateSync } from 'node:zlib';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { feature } from 'topojson-client';

const W = 1024;
const H = 512;
const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const require = createRequire(import.meta.url);
const topo = JSON.parse(readFileSync(require.resolve('world-atlas/land-50m.json'), 'utf8'));
const land = feature(topo, topo.objects.land);

// every ring of every polygon, as [lon, lat] points. Rings that cross the antimeridian
// are unwrapped into one continuous run of longitudes and drawn three times (shifted by
// -360, 0 and +360); a ring that goes all the way round a pole is closed over the pole.
const rings = [];
for (const f of land.features ?? [land]) {
  const g = f.geometry;
  const polys = g.type === 'Polygon' ? [g.coordinates] : g.coordinates;
  for (const poly of polys) {
    for (const ring of poly) {
      const pts = [[ring[0][0], ring[0][1]]];
      for (let i = 1; i < ring.length; i++) {
        let x = ring[i][0];
        const px = pts[i - 1][0];
        while (x - px > 180) x -= 360;
        while (x - px < -180) x += 360;
        pts.push([x, ring[i][1]]);
      }
      const net = pts[pts.length - 1][0] - pts[0][0];
      if (Math.abs(net) > 180) {
        const pole = pts.reduce((a, p) => a + p[1], 0) / pts.length > 0 ? 90 : -90;
        pts.push([pts[pts.length - 1][0], pole], [pts[0][0], pole], pts[0]);
      }
      for (const shift of [-360, 0, 360]) rings.push(pts.map(([x, y]) => [x + shift, y]));
    }
  }
}

// even-odd scanline fill at pixel centres
const mask = new Uint8Array(W * H);
for (let y = 0; y < H; y++) {
  const lat = 90 - ((y + 0.5) * 180) / H;
  const xs = [];
  for (const ring of rings) {
    for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
      const [x1, y1] = ring[j];
      const [x2, y2] = ring[i];
      if ((y1 > lat) !== (y2 > lat)) xs.push(x1 + ((lat - y1) / (y2 - y1)) * (x2 - x1));
    }
  }
  xs.sort((a, b) => a - b);
  for (let k = 0; k + 1 < xs.length; k += 2) {
    const a = Math.max(0, Math.ceil(((xs[k] + 180) / 360) * W - 0.5));
    const b = Math.min(W - 1, Math.floor(((xs[k + 1] + 180) / 360) * W - 0.5));
    for (let x = a; x <= b; x++) mask[y * W + x] = 1;
  }
}

// run lengths per row, sea first
const bytes = [];
const varint = (n) => {
  do {
    let b = n & 0x7f;
    n >>>= 7;
    if (n) b |= 0x80;
    bytes.push(b);
  } while (n);
};
let landPx = 0;
for (let y = 0; y < H; y++) {
  let v = 0;
  let run = 0;
  for (let x = 0; x < W; x++) {
    const m = mask[y * W + x];
    landPx += m;
    if (m === v) run++;
    else {
      varint(run);
      v = m;
      run = 1;
    }
  }
  varint(run);
}
const b64 = Buffer.from(bytes).toString('base64');
const out = `/* Generated by scripts/build-earth.mjs from Natural Earth 1:50m land (public domain).
 * ${W} x ${H} equirectangular land mask, row 0 at +90 latitude, column 0 at -180 longitude;
 * per row, alternating run lengths (sea first) as LEB128 varints, base64. Do not edit. */
export const EARTH_MASK = {
  w: ${W},
  h: ${H},
  runs: '${b64}',
};
`;
writeFileSync(join(root, 'web/src/storm/earthMask.ts'), out);
console.log(`earth mask ${W}x${H}: ${(landPx / (W * H) * 100).toFixed(1)}% land, ${bytes.length} bytes, ${b64.length} base64`);

// optional preview, a grey PNG
const pi = process.argv.indexOf('--preview');
if (pi > 0) {
  const raw = Buffer.alloc((W + 1) * H);
  for (let y = 0; y < H; y++) for (let x = 0; x < W; x++) raw[y * (W + 1) + 1 + x] = mask[y * W + x] ? 220 : 30;
  const crcTable = Array.from({ length: 256 }, (_, n) => {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    return c >>> 0;
  });
  const crc = (buf) => {
    let c = 0xffffffff;
    for (const b of buf) c = crcTable[(c ^ b) & 0xff] ^ (c >>> 8);
    return (c ^ 0xffffffff) >>> 0;
  };
  const chunk = (type, data) => {
    const len = Buffer.alloc(4);
    len.writeUInt32BE(data.length);
    const td = Buffer.concat([Buffer.from(type), data]);
    const c = Buffer.alloc(4);
    c.writeUInt32BE(crc(td));
    return Buffer.concat([len, td, c]);
  };
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(W, 0);
  ihdr.writeUInt32BE(H, 4);
  ihdr[8] = 8;
  ihdr[9] = 0;
  writeFileSync(
    process.argv[pi + 1],
    Buffer.concat([Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]), chunk('IHDR', ihdr), chunk('IDAT', deflateSync(raw)), chunk('IEND', Buffer.alloc(0))]),
  );
}
